- cmd/starboard/main.go
- go.sum
> fix: Load all known client-go auth plugins

- pkg/find/vulnerabilities/trivy/scanner.go
> fix: Pin Trivy to v0.8.0

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_enhancement_request.md
- .github/ISSUE_TEMPLATE/general_comment.md
- README.md
> docs: Add issue templates and badges

- README.md
Update the Readme, related to [Submit starboard CLI to krew-index](https://github.com/aquasecurity/starboard/issues/8)
> chore: Update readme to use krew

- pkg/kubebench/converter.go
- pkg/kubebench/scanner.go
- pkg/kubehunter/model.go
- pkg/kubehunter/scanner.go
> fix(ScannerCLI): kube-bench and kube-hunter do not respect --delete-scan-job flag

- pkg/find/vulnerabilities/trivy/scanner.go
- pkg/kubebench/scanner.go
- pkg/kubehunter/scanner.go
- pkg/polaris/scanner.go
Settings request and limits resources on scan jobs. Issue https://github.com/aquasecurity/starboard/issues/64
> chore: resource request and limits on scan jobs

- .github/workflows/codeql-analysis.yml
> chore: Update CodeQL config

- .github/workflows/codeql-analysis.yml
- cmd/starboard/main.go
> chore: Tune CodeQL

- pkg/find/vulnerabilities/crd/writer.go
This PR changes the way we save vulnerability reports.
Up until now, each time a new vulnerability scan occurred, we created a new CR for that report.
Now, the mechanism works the same as `ConfigAudit` reports. we check if a report for that container already exists,
If it does, we update it. if not, then creating it.
> Removed Historical Vulnerability Reports Saving

- README.md
- itest/starboard_cli_test.go
- pkg/cmd/kube_bench.go
- pkg/find/vulnerabilities/crd/writer_test.go
- pkg/kube/starboard.go
- pkg/kubebench/crd/writer.go
- pkg/kubebench/crd/writer_test.go
- pkg/kubebench/writer.go
In the initial version of Starbaord we wanted to store historical
benchmark reports. However, we now think that it's more appropriate
to store only the latest report.
Resolves: #101
> feat: Create or update CISKubeBenchReports

- itest/starboard_cli_test.go
> test(integration): Find vulnerabilities in ReplicaSet

- .github/workflows/build.yaml
- .gitignore
- Makefile
- cmd/starboard/main.go
- go.mod
- go.sum
- itest/starboard_cli_test.go
- itest/suite_test.go
- pkg/cmd/root.go
> test: Merge codecov reports

- Makefile
- itest/starboard_cli_test.go
- itest/suite_test.go
- pkg/cmd/root.go
- pkg/cmd/version.go
- pkg/cmd/version_test.go
> test: Fix integration test for version subcommand

- README.md
> docs(README): Resize logo

- pkg/kubebench/converter.go
- pkg/kubebench/converter_test.go
- pkg/kubebench/scanner.go
- pkg/kubebench/testdata/goldenMultiple.json
- pkg/kubebench/testdata/goldenSingle.json
- pkg/kubebench/testdata/invalid.json
- pkg/kubebench/testdata/multiObjects.json
- pkg/kubebench/testdata/valid.json
> kubebench version -> 0.3.1, update conversion logic, add tests 

- itest/starboard_cli_test.go
- pkg/docker/config.go
- pkg/docker/config_test.go
- pkg/find/vulnerabilities/crd/writer_test.go
- pkg/find/vulnerabilities/trivy/converter_test.go
- pkg/kube/secret/manager.go
- pkg/kube/secret/manager_test.go
- pkg/kube/secrets/secrets.go
- pkg/kube/secrets/secrets_test.go
> fix: Find vulnerabilities in workloads running images from private DockerHub repositories

- Makefile
> Makefile error on not providing KUBECONFIG env var

- README.md
> docs: Update command to run Polaris

- .gitignore
- itest/starboard_cli_test.go
[Issue 140](https://github.com/aquasecurity/starboard/issues/140) - Create integration test for polaris
> Issue 140 - Create integration test for polaris

- README.md
- ROADMAP.md
> docs: Add Docker image release

- itest/starboard_cli_test.go
- itest/suite_test.go
[Issue-155](https://github.com/aquasecurity/starboard/issues/155) Create a new namespace for integration tests
> chore: itest namespace

- README.md
- kube/init/starboard-cm.yaml
- pkg/find/vulnerabilities/trivy/scanner.go
- pkg/kube/cr_manager.go
> Add trivy.imageRef config key to the starboard ConfigMap

- README.md
- pkg/find/vulnerabilities/trivy/scanner.go
> Add trivy.githubToken config key to the starboard ConfigMap

- cmd/starboard-operator/main.go
- cmd/starboard/main.go
- hack/tools.go
- itest/starboard_cli_test.go
- itest/suite_test.go
- kube/init/starboard-cm.yaml
- pkg/cmd/config.go
- pkg/cmd/find_vulnerabilities.go
- pkg/cmd/kube_bench.go
- pkg/cmd/root.go
- pkg/cmd/version.go
- pkg/find/vulnerabilities/trivy/converter.go
- pkg/find/vulnerabilities/trivy/converter_test.go
- pkg/find/vulnerabilities/trivy/scanner.go
- pkg/kube/cr_manager.go
- pkg/kube/starboard.go
- pkg/kubebench/converter.go
- pkg/kubebench/converter_test.go
- pkg/kubebench/scanner.go
- pkg/kubehunter/scanner.go
- pkg/operator/aqua/scanner.go
- pkg/operator/etc/config.go
- pkg/operator/scanner.go
- pkg/operator/trivy/scanner.go
- pkg/polaris/scanner.go
- pkg/starboard/config.go
- pkg/starboard/config_test.go
- pkg/starboard/constants.go
- pkg/starboard/constants_test.go
> refactor: Bump up kube-bench to v0.4.0

- .github/workflows/build.yaml
- .github/workflows/release.yaml
- .goreleaser.yaml
- Makefile
- deploy/olm/bundle/0.6.0/starboard-operator.v0.6.0.clusterserviceversion.yaml
- deploy/olm/bundle/starboard-operator.package.yaml
> chore: Update GoReleaser config

- go.mod
- itest/starboard_cli_test.go
Follow up for https://github.com/aquasecurity/starboard/pull/193#issuecomment-706969910
> test: Add integration test for 'get vulnerabilities' command

- pkg/operator/controller/job/job_controller.go
- pkg/vulnerabilityreport/store.go
- pkg/vulnerabilityreport/store_test.go
> refactor: Save VulnerabilityReports method

- cmd/starboard-operator/main.go
- pkg/cmd/commands.go
- pkg/cmd/find_vulnerabilities.go
- pkg/cmd/get_configaudit.go
- pkg/cmd/get_report.go
- pkg/cmd/get_vulnerabilities.go
- pkg/cmd/kube_bench.go
- pkg/cmd/polaris.go
- pkg/cmd/root.go
- pkg/find/vulnerabilities/trivy/scanner.go
- pkg/kubebench/crd/writer_test.go
- pkg/operator/controller/reconciler.go
- pkg/starboard/config.go
- pkg/vulnerabilityreport/builder.go
- pkg/vulnerabilityreport/builder_test.go
- pkg/vulnerabilityreport/scanner.go
- pkg/vulnerabilityreport/store_test.go
- pkg/vulnerabilityreport/writer.go
- pkg/vulnerabilityreport/writer_test.go
> refactor: Use common methods to write vulnerabilityreports

- .github/workflows/build.yaml
- Makefile
- cmd/starboard-operator/main.go
- itest/starboard-operator/starboard_operator_test.go
- itest/starboard-operator/suite_test.go
- itest/starboard/starboard_cli_test.go
- itest/starboard/suite_test.go
- pkg/operator/operator.go
> test: Scaffold integration test for operator

- .github/ISSUE_TEMPLATE/bug_report.md
- README.md
> docs: Fix typos

- .github/workflows/build.yaml
- pkg/cmd/find_vulnerabilities.go
- pkg/cmd/kube_bench.go
- pkg/cmd/kube_hunter.go
- pkg/cmd/polaris.go
- pkg/cmd/scan_ciskubebench.go
- pkg/cmd/scan_configaudit.go
- pkg/cmd/scan_kubehunter.go
- pkg/cmd/scan_vulnerabilities.go
> fix: Compilation erros and remove duplicate code

- .github/workflows/release.yaml
> chore: Fix command to run integration tests in the release workflow

- .goreleaser.yaml
- deploy/helm/Chart.yaml
- deploy/helm/values.yaml
- deploy/static/05-starboard-operator.deployment.yaml
> release: Prepare v0.7.0

- deploy/olm/bundle/0.7.0/starboard-operator.v0.7.0.clusterserviceversion.yaml
- deploy/olm/bundle/0.7.0/vulnerabilityreports.v1alpha1.aquasecurity.github.io.crd.yaml
- deploy/olm/bundle/starboard-operator.package.yaml
> chore: Prepare OLM bundle v0.7.0

- deploy/helm/Chart.yaml
- deploy/static/05-starboard-operator.deployment.yaml
> release: Prepare v0.7.1

- docs/index.md
- mkdocs.yml
> docs: Init MkDocs

- docs/faq.md
- docs/index.md
- docs/troubleshooting.md
- mkdocs.yml
> docs: Skaffold MkDocs

- pkg/cmd/scan_vulnerabilities.go
- pkg/find/vulnerabilities/scanner.go
- pkg/operator/operator.go
- pkg/trivy/scanner.go
> refactor: Scanner CLI can easily swap the implementations of the underlying scanner

- .gitignore
- README.md
- docs/operator.md
- mkdocs.yml
> docs(operator): Configuration and install modes

- deploy/static/03-starboard-operator.clusterrole.yaml
> fix(deploy): Add statefulsets and daemonsets to RBAC config

- README.md
- deploy/static/05-starboard-operator.config.yaml
- docs/compatibility.md
- docs/configuration.md
- docs/integrations.md
- docs/operator.md
- mkdocs.yml
> docs(config): Add secret for sensitive settings

- docs/configuration.md
- pkg/starboard/config.go
- pkg/trivy/converter.go
- pkg/trivy/scanner.go
- pkg/trivy/scanner_test.go
- pkg/vulnerabilityreport/plugin.go
> feat(trivy): Authenticate Trivy client with token and custom headers

- .github/workflows/build.yaml
- .github/workflows/mkdocs-deploy.yaml
> chore: Switch to main branch

- .github/workflows/manual-ecr-publish.yaml
> chore: Publish Docker images to Amazon ECR

- pkg/cmd/get.go
- pkg/cmd/get_report.go
- pkg/report/html.go
- pkg/report/templates/default.qtpl
- pkg/report/templates/default.qtpl.go
> fix(cli): Do not panic when ConfigAuditReport is nil

- README.md
- mkdocs.yml
> docs: Fix link

- docs/configuration.md
- itest/starboard/starboard_cli_test.go
- mkdocs.yml
- pkg/cmd/scan_kubehunter.go
- pkg/kubebench/scanner.go
- pkg/kubehunter/model.go
- pkg/kubehunter/scanner.go
- pkg/starboard/config.go
- pkg/starboard/config_test.go
Introduce kube-hunter.imageRef config param.
> feat: Bump up kube-hunter to v0.4.0

- deploy/init/03-starboard.cm.yaml
- docs/configuration.md
- itest/starboard/starboard_cli_test.go
- pkg/cmd/scan_configaudit.go
- pkg/cmd/scan_kubehunter.go
- pkg/polaris/converter.go
- pkg/polaris/converter_test.go
- pkg/polaris/scanner.go
- pkg/starboard/config.go
> chore: Bump up Polaris to v3.0

- docs/integrations/lens.md
- docs/integrations/vulnerability-scanners/aqua-enterprise.md
- docs/integrations/vulnerability-scanners/index.md
- docs/integrations/vulnerability-scanners/trivy.md
- mkdocs.yml
> docs: Refactor vulnerability scanners section

- .github/workflows/build.yaml
- .github/workflows/release.yaml
> chore: Refactor release workflow

- deploy/static/05-starboard-operator.config.yaml
- deploy/static/06-starboard-operator.deployment.yaml
- docs/operator/configuration.md
> chore(deploy): Update static deployment descriptors

- docs/operator/installation/kubectl.md
> docs(deploy): Fix uninstall command

- docs/operator/installation/helm.md
- docs/operator/installation/kubectl.md
> docs(deploy): Update Helm install steps

- deploy/helm/Chart.yaml
- deploy/static/06-starboard-operator.deployment.yaml
> release: Prepare v0.8.0

- .github/workflows/release.yaml
> chore: Fix release workflow

- .github/workflows/build.yaml
- .github/workflows/release.yaml
- .goreleaser.yaml
> chore: Verify code in parallel in GitHub Actions workflow

- Makefile
- pkg/operator/controller/job/job_controller.go
- pkg/operator/controller/pod/pod_controller.go
- pkg/operator/predicate/predicate.go
- pkg/operator/predicate/predicate_suite_test.go
- pkg/operator/predicate/predicate_test.go
- pkg/resources/resources.go
> refactor(operator): Use predicates to filter out events added to a worker queue

- .github/workflows/build.yaml
- itest/starboard-operator/starboard_operator_test.go
- itest/starboard-operator/suite_test.go
> test(operator): Test that ConfigAuditReport is created

- .github/workflows/release.yaml
> fix: Integration tests runner in release workflow

- deploy/helm/Chart.yaml
- deploy/static/06-starboard-operator.deployment.yaml
> release: Prepare v0.9.0

- .github/workflows/mkdocs-deploy.yaml
- Makefile
- build/mkdocs-material/Dockerfile
- docs/index.md
- docs/operator/installation/helm.md
- docs/operator/installation/kubectl.md
- docs/operator/installation/olm.md
- mkdocs.yml
> chore: Integrate MkDocs with jimporter/mike

- README.md
> docs: Fix links to the latest docs

- docs/cli/index.md
- docs/cli/installation/docker.md
- docs/cli/installation/krew.md
- docs/cli/installation/source.md
- docs/index.md
- docs/integrations/lens.md
- docs/integrations/vulnerability-scanners/aqua-enterprise.md
- docs/integrations/vulnerability-scanners/index.md
- docs/operator/getting-started.md
- docs/operator/index.md
- docs/operator/installation/helm.md
- docs/operator/installation/kubectl.md
- docs/operator/installation/olm.md
- docs/settings.md
- mkdocs.yml
> docs: Use variables

- deploy/helm/Chart.yaml
- deploy/static/06-starboard-operator.deployment.yaml
- docs/crds.md
- docs/settings.md
- mkdocs.yml
> release: Prepare v0.9.1

- mkdocs.yml
> docs: Prepare v0.9.1

- mkdocs.yml
> docs: Enable search plugin

- pkg/report/html.go
- pkg/report/templates/default.qtpl
- pkg/report/templates/default.qtpl.go
- pkg/vulnerabilityreport/sort.go
- pkg/vulnerabilityreport/sort_test.go
Other minor enhancements:
- Order vulnerabilities by severity
- Add warnings count to config audit summary
- Format date
Resolves: #156
> fix: Aqua logo in HTML report

- deploy/helm/Chart.yaml
- deploy/static/06-starboard-operator.deployment.yaml
> release: Prepare v0.9.2

- mkdocs.yml
> docs: Prepare v0.9.2

- .github/workflows/build.yaml
- itest/starboard/starboard_cli_test.go
- pkg/cmd/get_report.go
- pkg/cmd/get_vulnerabilities.go
- pkg/cmd/scan_vulnerabilities.go
- pkg/kube/rs/rs.go
- pkg/report/html.go
- pkg/vulnerabilityreport/io.go
- pkg/vulnerabilityreport/io_test.go
> Get vulnerabilities from replicaset in same hierarchy

- deploy/crd/ciskubebenchreports.crd.yaml
- deploy/crd/configauditreports.crd.yaml
- deploy/crd/kubehunterreports.crd.yaml
- deploy/crd/vulnerabilityreports.crd.yaml
- pkg/apis/aquasecurity/v1alpha1/cis_kube_bench_types.go
- pkg/apis/aquasecurity/v1alpha1/config_audit_types.go
- pkg/apis/aquasecurity/v1alpha1/kube_hunter_types.go
- pkg/apis/aquasecurity/v1alpha1/vulnerability_types.go
- pkg/cmd/cleanup.go
- pkg/cmd/init.go
- pkg/generated/clientset/versioned/fake/register.go
- pkg/generated/listers/aquasecurity/v1alpha1/ciskubebenchreport.go
- pkg/generated/listers/aquasecurity/v1alpha1/configauditreport.go
- pkg/generated/listers/aquasecurity/v1alpha1/kubehunterreport.go
- pkg/generated/listers/aquasecurity/v1alpha1/vulnerabilityreport.go
- pkg/kube/cr_manager.go
> chore: Upgrade CRD apiVersion from apiextensions.k8s.io/v1beta1 to apiextensions.k8s.io/v1

- deploy/static/05-starboard-operator.config.yaml
- pkg/cmd/polaris.go
- pkg/cmd/root.go
- pkg/cmd/scan.go
- pkg/cmd/scan_configaudit.go
> refactor: Use factory to instantiate ConfigAuditReport plugins

- pkg/cmd/get_report.go
- pkg/report/html.go
> feat(cli): Update description of get report command

- itest/starboard-operator/starboard_operator_test.go
- itest/starboard-operator/suite_test.go
- itest/starboard/starboard_cli_test.go
- pkg/configauditreport/builder.go
- pkg/configauditreport/builder_test.go
- pkg/configauditreport/scanner.go
- pkg/kube/object.go
- pkg/operator/controller/ciskubebenchreport.go
- pkg/operator/controller/configauditreport.go
- pkg/operator/controller/owner_resolver.go
- pkg/operator/controller/vulnerabilityreport.go
- pkg/operator/predicate/predicate.go
- pkg/operator/predicate/predicate_test.go
- pkg/starboard/config.go
> feat: Deleting a ConfigAuditReport should trigger rescan

- Makefile
- pkg/kube/doc.go
- pkg/kube/object.go
- pkg/kube/object_test.go
- pkg/kube/resources.go
- pkg/kube/resources_test.go
- pkg/operator/controller/configauditreport.go
- pkg/operator/controller/vulnerabilityreport.go
- pkg/plugin/trivy/plugin.go
- pkg/resources/doc.go
- pkg/vulnerabilityreport/scanner.go
> refactor: Merge resources package with kube package

- CONTRIBUTING.md
- pkg/configauditreport/plugin.go
- pkg/configauditreport/scanner.go
- pkg/kube/object.go
- pkg/operator/controller/configauditreport.go
- pkg/plugin/polaris/plugin.go
- pkg/plugin/polaris/plugin_test.go
> refactor: Remove redundant args passed to configauditreport.Plugin

- CONTRIBUTING.md
- deploy/helm/templates/rbac.yaml
- deploy/static/03-starboard-operator.clusterrole.yaml
- pkg/operator/controller/ciskubebenchreport.go
- pkg/operator/controller/configauditreport.go
- pkg/operator/controller/vulnerabilityreport.go
> chore: Update deployment descriptors

- .github/workflows/publish-helm-chart.yaml
> chore: Trigger Helm chart publishing workflow manually

- docs/cli/getting-started.md
- docs/operator/getting-started.md
- docs/operator/index.md
- docs/operator/installation/helm.md
- docs/operator/installation/kubectl.md
> docs: Update docs for release v0.10.0

- deploy/helm/Chart.yaml
- deploy/helm/templates/configmap.yaml
- deploy/helm/values.yaml
- deploy/static/06-starboard-operator.deployment.yaml
- docs/operator/installation/helm.md
- mkdocs.yml
- pkg/operator/controller/configauditreport.go
> release: Prepare v0.10.0-rc2

- deploy/helm/values.yaml
- deploy/static/05-starboard-operator.config.yaml
- docs/settings.md
- itest/starboard/starboard_cli_test.go
- pkg/plugin/polaris/plugin_test.go
- pkg/starboard/config.go
Updates Polaris from v3.0 to v3.2
Resolves #433
> chore: Bump up Polaris from v3.0 to v3.2

- deploy/helm/templates/configmap.yaml
- deploy/helm/values.yaml
- docs/settings.md
- pkg/plugin/trivy/plugin.go
- pkg/plugin/trivy/plugin_test.go
> Add more proxy settings for Trivy

- CONTRIBUTING.md
- deploy/helm/templates/configmap.yaml
- deploy/helm/values.yaml
- pkg/plugin/trivy/plugin.go
- pkg/plugin/trivy/plugin_test.go
> chore: Fix code formatting

- itest/starboard-operator/starboard_operator_test.go
- itest/starboard/starboard_cli_test.go
- itest/starboard/suite_test.go
> refactor: Use client.Client in integration test

- itest/helper/helper.go
- itest/starboard-operator/starboard_operator_test.go
- itest/starboard-operator/suite_test.go
- itest/starboard/starboard_cli_test.go
> refactor: Use client.Client in integration test for operator

- pkg/cmd/scan_configaudit.go
- pkg/operator/operator.go
- pkg/plugin/factory.go
- pkg/starboard/plugin.go
- pkg/starboard/plugin_test.go
> feat: Add plugin name and config getter to PluginContext

- CONTRIBUTING.md
- Makefile
- deploy/static/03-starboard-operator.clusterrole.yaml
- deploy/static/05-starboard-operator.config.yaml
- pkg/cmd/scan_vulnerabilities.go
- pkg/configauditreport/builder.go
- pkg/configauditreport/builder_test.go
- pkg/configauditreport/doc.go
- pkg/configauditreport/plugin.go
- pkg/kube/starboard.go
- pkg/operator/controller/configauditreport.go
- pkg/operator/controller/plugins_config.go
- pkg/operator/etc/config.go
- pkg/operator/operator.go
- pkg/plugin/conftest/doc.go
- pkg/plugin/conftest/plugin.go
- pkg/plugin/conftest/plugin_test.go
- pkg/plugin/conftest/types.go
- pkg/plugin/conftest/types_test.go
- pkg/plugin/factory.go
- pkg/plugin/polaris/plugin.go
- pkg/starboard/config.go
- pkg/vulnerabilityreport/scanner.go
> poc: Integrate Conftest as ConfigAuditReports scanner

- deploy/helm/templates/deployment.yaml
- deploy/helm/templates/rbac.yaml
Hi,
this is the pull request to fix the issues reported in #485
> Fix helm chart issue: error calling gt: incompatible types for comparison

- itest/starboard-operator/starboard_operator_test.go
Resolves https://github.com/aquasecurity/starboard/issues/453
> test(operator): Assert that Deployment is rescanned when the ConfigAuditReport is deleted

- pkg/operator/controller/limit_checker.go
- pkg/plugin/conftest/plugin.go
- pkg/plugin/conftest/plugin_test.go
- pkg/plugin/polaris/model_test.go
- pkg/plugin/polaris/plugin_test.go
> fix(conftest): Do not show negative pass count

- pkg/report/templates/namespace_report.qtpl
- pkg/report/templates/namespace_report.qtpl.go
> fix: Rearrange sections in HTML report for namespace

- CONTRIBUTING.md
- deploy/helm/templates/rbac.yaml
> fix(helm): Add permission to delete ConfigAuditReports

- pkg/operator/controller/configauditreport.go
> fix(operator): Delete scan job for workload that has been deleted

- deploy/helm/Chart.yaml
- deploy/static/06-starboard-operator.deployment.yaml
- mkdocs.yml
> release: Prepare v0.10.0

- mkdocs.yml
> docs: Release v0.10.0

- mkdocs.yml
> docs: Use mike as version provider

- .gitignore
- mkdocs.yml
- overrides/main.html
> docs: Display version warning

- pkg/plugin/trivy/plugin.go
- pkg/plugin/trivy/plugin_test.go
> Fix Trivy arguments

- itest/matcher/matcher.go
- itest/matcher/matcher_test.go
- itest/starboard/starboard_cli_test.go
- itest/starboard/suite_test.go
Resolves https://github.com/aquasecurity/starboard/issues/479
> test(cli): Add integration test for `Conftest` scanner

- docs/integrations/config-checkers/conftest.md
- docs/integrations/vulnerability-scanners/trivy.md
- docs/operator/installation/olm.md
> docs(trivy): Update links and fix formatting

- deploy/helm/Chart.yaml
- deploy/static/06-starboard-operator.deployment.yaml
- mkdocs.yml
> release: Prepare v0.10.1-rc1

- pkg/kubebench/scanner.go
- pkg/operator/controller/ciskubebenchreport.go
> fix(cisbenchmark): Error creating scan Job - label has more than 63 characters

- deploy/helm/values.yaml
- deploy/static/06-starboard-operator.deployment.yaml
> fix: Cannot deploy Starboard Operator on OpenShift Container Platform

- deploy/helm/Chart.yaml
- deploy/static/06-starboard-operator.deployment.yaml
- mkdocs.yml
> release: Prepare v0.10.1

- mkdocs.yml
> docs: Prepare v0.10.1

- .github/workflows/build.yaml
- .github/workflows/mkdocs-deploy.yaml
- .github/workflows/release.yaml
> chore: Use the MKDOCS_AQUA_BOT secret to publish docs

- docs/cli/getting-started.md
- docs/index.md
- docs/integrations/config-checkers/index.md
- docs/integrations/config-checkers/polaris.md
- docs/operator/getting-started.md
- mkdocs.yml
To preview the docs page:
```
make mkdocs-serve
```
And then open [http://localhost:8000](http://localhost:8000) in your web browser.
> docs: Describe Polaris plugin and give overview for configuration checkers

- cmd/starboard-operator/main.go
- itest/helper/helper.go
- itest/starboard-operator/starboard_operator_test.go
- itest/starboard-operator/suite_test.go
- pkg/operator/etc/config.go
- pkg/operator/operator.go
> test: Gracefully shutdown operator in integration test

- .goreleaser.yaml
- deploy/helm/Chart.yaml
- deploy/static/06-starboard-operator.deployment.yaml
- mkdocs.yml
- pkg/kube/doc.go
- pkg/kubebench/doc.go
- pkg/kubehunter/doc.go
- pkg/plugin/aqua/client/doc.go
- pkg/plugin/aqua/doc.go
- pkg/plugin/aqua/scanner/api/doc.go
- pkg/plugin/aqua/scanner/cli/doc.go
- pkg/plugin/conftest/doc.go
- pkg/plugin/doc.go
- pkg/plugin/polaris/doc.go
- pkg/plugin/trivy/doc.go
- pkg/runner/doc.go
- pkg/starboard/doc.go
- pkg/vulnerabilityreport/doc.go
> release: Prepare v0.10.2-rc1

- README.md
- deploy/helm/Chart.yaml
- mkdocs.yml
> docs: Prepare v0.10.2

- deploy/helm/Chart.yaml
- deploy/static/06-starboard-operator.deployment.yaml
- mkdocs.yml
> release: Prepare v0.10.3

- mkdocs.yml
> docs: Prepare v0.10.3

- docs/cli/getting-started.md
- docs/operator/getting-started.md
> docs: Explain how operator handles scaled workloads

- docs/settings.md
- pkg/cmd/scan_ciskubebenchreports.go
- pkg/cmd/scan_configauditreports.go
- pkg/cmd/scan_kubehunterreports.go
- pkg/cmd/scan_vulnerabilityreports.go
- pkg/configauditreport/builder.go
- pkg/configauditreport/plugin_test.go
- pkg/configauditreport/scanner.go
- pkg/kube/starboard.go
- pkg/kubebench/scanner.go
- pkg/kubehunter/model_test.go
- pkg/kubehunter/scanner.go
- pkg/kubehunter/scanner_test.go
- pkg/operator/controller/ciskubebenchreport.go
- pkg/operator/controller/configauditreport.go
- pkg/starboard/config_test.go
- pkg/vulnerabilityreport/scanner.go
> feat: Apply configurable tolerations to all kinds of scanners

- itest/starboard/starboard_cli_test.go
Resolves https://github.com/aquasecurity/starboard/issues/561
> fix: Flaky CLI Integration Test

- .github/workflows/publish-helm-chart.yaml
> chore: Replace ORG_GITHUB_TOKEN secret with ORG_REPO_TOKEN

- pkg/cmd/scan_vulnerabilityreports.go
- pkg/operator/controller/vulnerabilityreport.go
- pkg/operator/operator.go
- pkg/plugin/aqua/plugin.go
- pkg/plugin/factory.go
- pkg/plugin/trivy/plugin.go
- pkg/plugin/trivy/plugin_test.go
- pkg/vulnerabilityreport/plugin.go
- pkg/vulnerabilityreport/scanner.go
> feat: Add PluginContext to vulnerability scan plugins

- pkg/plugin/conftest/plugin.go
- pkg/starboard/plugin.go
- pkg/starboard/plugin_test.go
> refactor: Define PluginConfig object

- deploy/helm/templates/config.yaml
- deploy/helm/values.yaml
- docs/integrations/vulnerability-scanners/aqua-enterprise.md
- pkg/plugin/aqua/plugin.go
- pkg/plugin/aqua/plugin_test.go
- pkg/plugin/factory.go
- pkg/starboard/config.go
> refactor: Remove Aqua settings from generic starboard ConfigMap

- deploy/helm/templates/config.yaml
- deploy/helm/values.yaml
- docs/settings.md
- pkg/configauditreport/builder.go
> feat(helm): Configure scanner pods tolerations and annotations

- pkg/plugin/trivy/plugin.go
- pkg/plugin/trivy/plugin_test.go
- pkg/starboard/config.go
- pkg/starboard/config_test.go
> refactor: Move Trivy config utilities to trivy package

- pkg/operator/controller/ciskubebenchreport.go
- pkg/operator/predicate/predicate.go
Resolves: https://github.com/aquasecurity/starboard/issues/592
> fix(cisbenchmark): Skip Windows Node

- pkg/cmd/cleanup.go
- pkg/cmd/doc.go
- pkg/cmd/init.go
- pkg/cmd/installer.go
- pkg/cmd/root.go
- pkg/configauditreport/doc.go
- pkg/docker/doc.go
- pkg/operator/doc.go
> refactor: Rename kube.CR_Manager to cmd.Installer

- pkg/plugin/trivy/plugin.go
> chore: Use the same receiver name for Trivy plugin

- deploy/helm/values.yaml
- deploy/static/05-starboard-operator.config.yaml
- docs/settings.md
- itest/starboard/starboard_cli_test.go
- pkg/kubebench/scanner_test.go
- pkg/starboard/config.go
> chore: Bump up kube-bench from v0.5.0 to v0.6.3

- pkg/plugin/conftest/plugin_test.go
- pkg/plugin/trivy/plugin.go
- pkg/plugin/trivy/plugin_test.go
> test(trivy): Init method

- deploy/static/05-starboard-operator.config.yaml
- docs/settings.md
- pkg/plugin/polaris/plugin.go
- pkg/plugin/polaris/plugin_test.go
- pkg/plugin/trivy/plugin.go
- pkg/plugin/trivy/plugin_test.go
> feat(polaris): Allow configuration of resource request and limits

- .github/workflows/build.yaml
- .github/workflows/release.yaml
> chore(ci): Upgrade KIND from v0.9.0 to v0.11.1

- deploy/helm/values.yaml
- deploy/static/05-starboard-operator.config.yaml
- docs/integrations/config-checkers/polaris.md
- docs/settings.md
- pkg/plugin/polaris/plugin.go
- pkg/plugin/polaris/plugin_test.go
> chore(polaris): Rename properties to configure resource requirements and limits

- .github/workflows/build.yaml
- deploy/helm/values.yaml
- deploy/static/05-starboard-operator.config.yaml
- docs/integrations/config-checkers/polaris.md
- itest/matcher/matcher.go
- itest/matcher/matcher_test.go
- pkg/plugin/polaris/plugin.go
- pkg/plugin/polaris/plugin_test.go
> chore(polaris): upgrade polaris from v3.2 to v4.0

- .github/workflows/build.yaml
- build/mkdocs-material/Dockerfile
- docs/integrations/vulnerability-scanners/aqua-enterprise.md
- docs/integrations/vulnerability-scanners/trivy.md
- docs/settings.md
> docs: Update Starboard settings

- deploy/helm/values.yaml
- deploy/static/05-starboard-operator.config.yaml
- docs/integrations/vulnerability-scanners/trivy.md
- itest/matcher/matcher.go
- itest/matcher/matcher_test.go
- pkg/plugin/trivy/plugin.go
- pkg/plugin/trivy/plugin_test.go
> chore(trivy): Upgrade from v0.16.0 to v0.19.2

- deploy/static/06-starboard-operator.deployment.yaml
- mkdocs.yml
> release: Prepare v0.11.0-rc1

- .github/workflows/build.yaml
- .github/workflows/release.yaml
- build/scanner-aqua/Dockerfile
- build/starboard-operator/Dockerfile
- build/starboard/Dockerfile
- deploy/helm/Chart.yaml
- deploy/static/06-starboard-operator.deployment.yaml
- mkdocs.yml
> release: Prepare v0.11.0

- mkdocs.yml
> docs: Release v0.11.0

- CONTRIBUTING.md
- docs/operator/installation/olm.md
> docs: Update to new community operators repository

- .goreleaser.yaml
- deploy/helm/Chart.yaml
- deploy/static/06-starboard-operator.deployment.yaml
- mkdocs.yml
> release: Prepare v0.12.0-rc1

- docs/settings.md
- pkg/kubehunter/scanner.go
- pkg/starboard/config.go
> chore(kube-hunter): Bump up kube-hunter from v0.4.1 to v0.6.1

- pkg/plugin/polaris/plugin.go
> fix(polaris): Add Deployment to supported kinds

- deploy/helm/Chart.yaml
- deploy/static/06-starboard-operator.deployment.yaml
- mkdocs.yml
> release: Prepare v0.12.0-rc3

- deploy/helm/Chart.yaml
- deploy/static/06-starboard-operator.deployment.yaml
- mkdocs.yml
> release: Prepare v0.12.0-rc4

- CONTRIBUTING.md
> docs: Update contributing guide

- deploy/helm/Chart.yaml
- deploy/static/06-starboard-operator.deployment.yaml
- mkdocs.yml
> release: Prepare v0.12.0

- mkdocs.yml
> docs: Prepare v0.12.0

- pkg/cmd/get.go
- pkg/cmd/get_configauditreports.go
- pkg/cmd/get_vulnerabilityreports.go
> chore(cli): Rename get subcommands to be consistent with scan subcommands

- deploy/helm/Chart.yaml
- deploy/static/04-starboard-operator.deployment.yaml
- mkdocs.yml
> release: Prepare v0.13.0-rc2

- docs/cli/getting-started.md
> docs(cli): update getting started guide

- README.md
- docs/cli/getting-started.md
- docs/cli/index.md
- docs/index.md
- docs/integrations/infra-scanners/index.md
- docs/operator/getting-started.md
- docs/operator/index.md
> docs: review and update docs

- deploy/helm/Chart.yaml
- deploy/static/02-starboard-operator.rbac.yaml
- deploy/static/03-starboard-operator.config.yaml
- deploy/static/04-starboard-operator.deployment.yaml
- mkdocs.yml
> release: prepare v0.13.0

- docs/cli/getting-started.md
- mkdocs.yml
> docs: release v0.13.0

- docs/integrations/config-checkers/conftest.md
> docs: fix helm command to install starboard with conftest policies

- README.md
- docs/index.md
> docs: update README.md

- NOTICE
- README.md
- build/mkdocs-material/Dockerfile
- docs/index.md
- mkdocs.yml
> docs: update project overview

- README.md
- docs/index.md
> docs: add high-level diagram

- .github/workflows/publish-helm-chart.yaml
Adding a lint and testing step in github action to the helm chart
> chore: helm testing gh-action

- mkdocs.yml
> docs: release v0.13.1

- .github/workflows/build.yaml
- .github/workflows/release.yaml
- itest/helper/helper.go
- itest/starboard/starboard_cli_test.go
- itest/starboard/suite_test.go
> test(cli): scanning images from private registries

- deploy/helm/Chart.yaml
- deploy/static/02-starboard-operator.rbac.yaml
- deploy/static/03-starboard-operator.config.yaml
- deploy/static/04-starboard-operator.deployment.yaml
- mkdocs.yml
> release: prepare v0.13.2

- docs/design/ttl_scans.md
A start for a design proposal for ttl on scans #537 
Signed-off-by: Edvin Norling <edvin.norling@xenit.se>
> docs: Design proposal for TTL scans

- .github/workflows/build.yaml
- deploy/helm/Chart.yaml
- deploy/static/02-starboard-operator.rbac.yaml
- deploy/static/03-starboard-operator.config.yaml
- deploy/static/04-starboard-operator.deployment.yaml
- mkdocs.yml
> release: prepare v0.14.0-rc1

- docs/design/design_trivy_file_system_scanner.md
> docs(design): update Scan Container Images with Trivy Filesystem Scanner

- deploy/helm/templates/deployment.yaml
- deploy/static/04-starboard-operator.deployment.yaml
- pkg/operator/etc/config.go
- pkg/starboard/config.go
- pkg/starboard/config_test.go
- pkg/starboard/constants.go
> refactor: review and cleanup starboard config package

- build/mkdocs-material/Dockerfile
- docs/cli/getting-started.md
- docs/index.md
- docs/operator/getting-started.md
> docs: revisit documentation pages for consistency

- deploy/crd/ciskubebenchreports.crd.yaml
- deploy/crd/clusterconfigauditreports.crd.yaml
- deploy/crd/clustervulnerabilityreports.crd.yaml
- deploy/crd/configauditreports.crd.yaml
- deploy/crd/kubehunterreports.crd.yaml
- deploy/crd/vulnerabilityreports.crd.yaml
- deploy/helm/Chart.yaml
- deploy/static/02-starboard-operator.rbac.yaml
- deploy/static/03-starboard-operator.config.yaml
- deploy/static/04-starboard-operator.deployment.yaml
> release: prepare v0.14.0-rc2

- deploy/crd/ciskubebenchreports.crd.yaml
- deploy/crd/clusterconfigauditreports.crd.yaml
- deploy/crd/clustervulnerabilityreports.crd.yaml
- deploy/crd/configauditreports.crd.yaml
- deploy/crd/kubehunterreports.crd.yaml
- deploy/crd/vulnerabilityreports.crd.yaml
- deploy/helm/Chart.yaml
- deploy/static/02-starboard-operator.rbac.yaml
- deploy/static/03-starboard-operator.config.yaml
- deploy/static/04-starboard-operator.deployment.yaml
> release: prepare v0.14.0

- deploy/helm/values.yaml
- deploy/static/03-starboard-operator.config.yaml
- docs/integrations/vulnerability-scanners/trivy.md
- itest/matcher/matcher.go
- itest/matcher/matcher_test.go
- pkg/plugin/trivy/plugin.go
- pkg/plugin/trivy/plugin_test.go
> chore(deps): bump Trivy from v0.20.0 to v0.22.0

- deploy/crd/ciskubebenchreports.crd.yaml
- deploy/crd/clusterconfigauditreports.crd.yaml
- deploy/crd/clustervulnerabilityreports.crd.yaml
- deploy/crd/configauditreports.crd.yaml
- deploy/crd/kubehunterreports.crd.yaml
- deploy/crd/vulnerabilityreports.crd.yaml
- deploy/helm/Chart.yaml
- deploy/static/02-starboard-operator.rbac.yaml
- deploy/static/03-starboard-operator.config.yaml
- deploy/static/04-starboard-operator.deployment.yaml
- mkdocs.yml
> release: prepare v0.14.1

- CONTRIBUTING.md
> docs(CONTRIBUTING.md): fix instructions to run integration tests

- .github/workflows/build.yaml
- .github/workflows/release.yaml
- .gitignore
- .goreleaser.yaml
- .krew.yaml
Supporting arm arch for : 
- binaries
- images
Signed-off-by: chen-keinan <hen.keinan@gmail.com>
> chore: support arm arch

- itest/matcher/matcher.go
- itest/matcher/matcher_test.go
- itest/starboard/starboard_cli_test.go
- pkg/plugin/conftest/plugin_test.go
- pkg/plugin/factory.go
- pkg/plugin/polaris/plugin.go
- pkg/plugin/polaris/plugin_test.go
- pkg/starboard/config.go
- pkg/starboard/config_test.go
> refactor: move plugin constants from generic starboard config

- deploy/helm/values.yaml
- deploy/static/03-starboard-operator.config.yaml
- docs/integrations/vulnerability-scanners/trivy.md
- itest/matcher/matcher.go
- itest/matcher/matcher_test.go
- pkg/plugin/trivy/plugin.go
- pkg/plugin/trivy/plugin_test.go
> chore(deps): bump Trivy from v0.22.0 to v0.23.0

- deploy/helm/values.yaml
- docs/design/design_associating_rego_policies_with_k8s_resources.md
- docs/integrations/config-checkers/conftest.md
- itest/matcher/matcher.go
- itest/starboard-operator/configauditreport/conftest/suite_test.go
- itest/starboard/suite_test.go
- pkg/plugin/conftest/plugin.go
- pkg/plugin/conftest/plugin_test.go
> chore(deps): bump Conftest from v0.28.2 to v0.30.0

- pkg/plugin/trivy/plugin.go
- pkg/plugin/trivy/plugin_test.go
Scan pods created by Starboard are immutable, i.e. have
read-only root filesystem. To enable fanal to write to
the temporary directory we must create the emptyDir volume
and mount it on the /tmp path. This patch is only applicable
to Trivy in Standalone mode.
Resolves: #944
> feat(trivy): mount emptyDir volume on /tmp path

- pkg/configauditreport/builder.go
- pkg/kube/object.go
- pkg/kube/object_test.go
- pkg/vulnerabilityreport/builder.go
> refactor: rename ObjectToObjectMetadata to ObjectToObjectMeta

- pkg/configauditreport/io.go
- pkg/kube/object.go
- pkg/kube/object_test.go
- pkg/operator/controller/configauditreport.go
- pkg/operator/controller/vulnerabilityreport.go
- pkg/vulnerabilityreport/io.go
> refactor: GetRelatedReplicasetName

- CONTRIBUTING.md
- deploy/static/kustomization.yaml
- deploy/static/starboard.yaml
- docs/operator/configuration.md
- docs/operator/installation/kubectl.md
> chore(operator): streamline installation with kubectl

- CONTRIBUTING.md
- docs/operator/installation/kubectl.md
- docs/operator/installation/olm.md
> chore(deps): upgrade OLM from v0.18.3 to v0.20.0

- pkg/apis/aquasecurity/v1alpha1/common_types.go
- pkg/apis/aquasecurity/v1alpha1/common_types_test.go
- pkg/kube/object.go
- pkg/kube/object_test.go
- pkg/plugin/conftest/plugin.go
- pkg/plugin/polaris/model.go
- pkg/plugin/polaris/plugin.go
> refactor: parse severity from name

- .github/workflows/build.yaml
- itest/starboard-operator/configauditreport/conftest/suite_test.go
> refactor(itest): create or update configuration objects

- docs/crds/configaudit-report.md
- pkg/apis/aquasecurity/v1alpha1/config_audit_types.go
- pkg/plugin/conftest/plugin.go
- pkg/plugin/conftest/plugin_test.go
- pkg/plugin/polaris/plugin.go
- pkg/plugin/polaris/plugin_test.go
> feat: allow config check to contain zero to many messages

- docs/design/design_compliance_report.md
Design for supporting dynamic compliance reports
Signed-off-by: chen-keinan <hen.keinan@gmail.com>
> docs: design compliance report 

- RELEASING.md
- deploy/static/01-starboard-operator.ns.yaml
> chore: update release checklist

- deploy/specs/nsa-1.0.yaml
- deploy/static/starboard.yaml
> chore: change NSA check 2.0  kind type

- .goreleaser.yaml
> fix(goreleaser): fix typo in container image name

- deploy/crd/ciskubebenchreports.crd.yaml
- deploy/crd/clustercompliancedetailreports.crd.yaml
- deploy/crd/clustercompliancereports.crd.yaml
- deploy/crd/clusterconfigauditreports.crd.yaml
- deploy/crd/clustervulnerabilityreports.crd.yaml
- deploy/crd/configauditreports.crd.yaml
- deploy/crd/kubehunterreports.crd.yaml
- deploy/crd/vulnerabilityreports.crd.yaml
- deploy/helm/Chart.yaml
- deploy/specs/nsa-1.0.yaml
- deploy/static/01-starboard-operator.ns.yaml
- deploy/static/02-starboard-operator.rbac.yaml
- deploy/static/03-starboard-operator.config.yaml
- deploy/static/04-starboard-operator.policies.yaml
- deploy/static/05-starboard-operator.deployment.yaml
- deploy/static/starboard.yaml
> release: prepare v0.15.0-rc2

- .goreleaser.yaml
> chore(release): skip publishing to ECR

- deploy/crd/ciskubebenchreports.crd.yaml
- deploy/crd/clustercompliancedetailreports.crd.yaml
- deploy/crd/clustercompliancereports.crd.yaml
- deploy/crd/clusterconfigauditreports.crd.yaml
- deploy/crd/clustervulnerabilityreports.crd.yaml
- deploy/crd/configauditreports.crd.yaml
- deploy/crd/kubehunterreports.crd.yaml
- deploy/crd/vulnerabilityreports.crd.yaml
- deploy/helm/Chart.yaml
- deploy/specs/nsa-1.0.yaml
- deploy/static/01-starboard-operator.ns.yaml
- deploy/static/02-starboard-operator.rbac.yaml
- deploy/static/03-starboard-operator.config.yaml
- deploy/static/04-starboard-operator.policies.yaml
- deploy/static/05-starboard-operator.deployment.yaml
- deploy/static/starboard.yaml
> release: prepare v0.15.0-rc3

- .goreleaser.yaml
- deploy/crd/ciskubebenchreports.crd.yaml
- deploy/crd/clustercompliancedetailreports.crd.yaml
- deploy/crd/clustercompliancereports.crd.yaml
- deploy/crd/clusterconfigauditreports.crd.yaml
- deploy/crd/clustervulnerabilityreports.crd.yaml
- deploy/crd/configauditreports.crd.yaml
- deploy/crd/kubehunterreports.crd.yaml
- deploy/crd/vulnerabilityreports.crd.yaml
- deploy/helm/Chart.yaml
- deploy/specs/nsa-1.0.yaml
- deploy/static/01-starboard-operator.ns.yaml
- deploy/static/02-starboard-operator.rbac.yaml
- deploy/static/03-starboard-operator.config.yaml
- deploy/static/04-starboard-operator.policies.yaml
- deploy/static/05-starboard-operator.deployment.yaml
- deploy/static/starboard.yaml
> release: prepare v0.15.0-rc4

- docs/cli/getting-started.md
- docs/cli/installation/binary-releases.md
- docs/operator/installation/helm.md
- docs/operator/installation/olm.md
> docs: update installation guides for v0.15.0

- pkg/operator/operator.go
- pkg/vulnerabilityreport/controller.go
- pkg/vulnerabilityreport/controller_test.go
> refactor: VulnerabilityReportReconciler to WorkloadController

- overrides/main.html
- pkg/plugin/trivy/plugin.go
- pkg/vulnerabilityreport/builder.go
> feat(vulnerabilityreports): use deterministic names for secrets associated with scan jobs

- build/mkdocs-material/Dockerfile
- deploy/helm/templates/NOTES.txt
- deploy/helm/templates/deployment.yaml
- deploy/helm/values.yaml
- deploy/static/05-starboard-operator.deployment.yaml
- deploy/static/starboard.yaml
- docs/operator/getting-started.md
- docs/operator/installation/helm.md
- docs/operator/installation/kubectl.md
- docs/operator/installation/olm.md
- pkg/operator/operator.go
- pkg/operator/predicate/predicate.go
> chore(deploy): configure operator to select all namespaces, except kube-system and starboard-system by default

- deploy/crd/ciskubebenchreports.crd.yaml
- deploy/crd/clustercompliancedetailreports.crd.yaml
- deploy/crd/clustercompliancereports.crd.yaml
- deploy/crd/clusterconfigauditreports.crd.yaml
- deploy/crd/clustervulnerabilityreports.crd.yaml
- deploy/crd/configauditreports.crd.yaml
- deploy/crd/kubehunterreports.crd.yaml
- deploy/crd/vulnerabilityreports.crd.yaml
- deploy/helm/Chart.yaml
- deploy/specs/nsa-1.0.yaml
- deploy/static/01-starboard-operator.ns.yaml
- deploy/static/02-starboard-operator.rbac.yaml
- deploy/static/03-starboard-operator.config.yaml
- deploy/static/04-starboard-operator.policies.yaml
- deploy/static/05-starboard-operator.deployment.yaml
- deploy/static/starboard.yaml
> release: prepare v0.15.0-rc7

- docs/operator/installation/olm.md
- docs/settings.md
> docs(olm): fix OperatorGroup to select all namespaces

- deploy/specs/nsa-1.0.yaml
> chore: nsa spec data typo

- docs/design/caching_scan_results_by_repo_digest.md
Solves the TODO defined in the document and follows existing solutions in starboard.
Signed-off-by: Edvin Norling <edvin.norling@xenit.se>
> [docs](design): ClusterVulnerabilityReport life-cycle

- docs/cli/troubleshooting.md
- docs/operator/troubleshooting.md
- mkdocs.yml
Basic outline of ways to troubleshoot the Starboard Operator. I would assume that over time, we will add more issues etc.
Let me know if you would like it written more of a checklist vs a guide or to reference any additional scenarios.
[Issue](#884)
> Docs troubleshooting for Starboard Operator

- .github/workflows/build.yaml
- deploy/crd/ciskubebenchreports.crd.yaml
- deploy/crd/clustercompliancedetailreports.crd.yaml
- deploy/crd/clustercompliancereports.crd.yaml
- deploy/crd/clusterconfigauditreports.crd.yaml
- deploy/crd/clustervulnerabilityreports.crd.yaml
- deploy/crd/configauditreports.crd.yaml
- deploy/crd/kubehunterreports.crd.yaml
- deploy/crd/vulnerabilityreports.crd.yaml
- deploy/helm/Chart.yaml
- deploy/specs/nsa-1.0.yaml
- deploy/static/01-starboard-operator.ns.yaml
- deploy/static/02-starboard-operator.rbac.yaml
- deploy/static/03-starboard-operator.config.yaml
- deploy/static/04-starboard-operator.policies.yaml
- deploy/static/05-starboard-operator.deployment.yaml
- deploy/static/starboard.yaml
- mkdocs.yml
> release: prepare v0.15.0

- CONTRIBUTING.md
update contribution convention guide
> docs: update contribution convention

- deploy/crd/ciskubebenchreports.crd.yaml
- deploy/crd/clustercompliancedetailreports.crd.yaml
- deploy/crd/clustercompliancereports.crd.yaml
- deploy/crd/clusterconfigauditreports.crd.yaml
- deploy/crd/clustervulnerabilityreports.crd.yaml
- deploy/crd/configauditreports.crd.yaml
- deploy/crd/kubehunterreports.crd.yaml
- deploy/crd/vulnerabilityreports.crd.yaml
- deploy/helm/Chart.yaml
- deploy/specs/nsa-1.0.yaml
- deploy/static/01-starboard-operator.ns.yaml
- deploy/static/02-starboard-operator.rbac.yaml
- deploy/static/03-starboard-operator.config.yaml
- deploy/static/04-starboard-operator.policies.yaml
- deploy/static/05-starboard-operator.deployment.yaml
- deploy/static/starboard.yaml
- mkdocs.yml
> release: prepare v0.15.2

- deploy/crd/ciskubebenchreports.crd.yaml
- deploy/crd/clustercompliancedetailreports.crd.yaml
- deploy/crd/clustercompliancereports.crd.yaml
- deploy/crd/clusterconfigauditreports.crd.yaml
- deploy/crd/clustervulnerabilityreports.crd.yaml
- deploy/crd/configauditreports.crd.yaml
- deploy/crd/kubehunterreports.crd.yaml
- deploy/crd/vulnerabilityreports.crd.yaml
- deploy/helm/Chart.yaml
- deploy/specs/nsa-1.0.yaml
- deploy/static/01-starboard-operator.ns.yaml
- deploy/static/02-starboard-operator.rbac.yaml
- deploy/static/03-starboard-operator.config.yaml
- deploy/static/04-starboard-operator.policies.yaml
- deploy/static/05-starboard-operator.deployment.yaml
- deploy/static/starboard.yaml
- mkdocs.yml
> release: v0.15.3

- deploy/crd/ciskubebenchreports.crd.yaml
- deploy/crd/clustercompliancedetailreports.crd.yaml
- deploy/crd/clustercompliancereports.crd.yaml
- deploy/crd/clusterconfigauditreports.crd.yaml
- deploy/crd/clustervulnerabilityreports.crd.yaml
- deploy/crd/configauditreports.crd.yaml
- deploy/crd/kubehunterreports.crd.yaml
- deploy/crd/vulnerabilityreports.crd.yaml
- deploy/helm/Chart.yaml
- deploy/specs/nsa-1.0.yaml
- deploy/static/01-starboard-operator.ns.yaml
- deploy/static/02-starboard-operator.rbac.yaml
- deploy/static/03-starboard-operator.config.yaml
- deploy/static/04-starboard-operator.policies.yaml
- deploy/static/05-starboard-operator.deployment.yaml
- deploy/static/starboard.yaml
- mkdocs.yml
> release: prepare v0.15.4

- pkg/plugin/trivy/plugin.go
- pkg/plugin/trivy/plugin_test.go
> chore: fix Go code formatting

- deploy/crd/ciskubebenchreports.crd.yaml
- deploy/crd/clustercompliancedetailreports.crd.yaml
- deploy/crd/clustercompliancereports.crd.yaml
- deploy/crd/clusterconfigauditreports.crd.yaml
- deploy/crd/clustervulnerabilityreports.crd.yaml
- deploy/crd/configauditreports.crd.yaml
- deploy/crd/kubehunterreports.crd.yaml
- deploy/crd/vulnerabilityreports.crd.yaml
- deploy/helm/Chart.yaml
- deploy/specs/nsa-1.0.yaml
- deploy/static/01-starboard-operator.ns.yaml
- deploy/static/02-starboard-operator.rbac.yaml
- deploy/static/03-starboard-operator.config.yaml
- deploy/static/04-starboard-operator.policies.yaml
- deploy/static/05-starboard-operator.deployment.yaml
- deploy/static/starboard.yaml
- mkdocs.yml
> release: prepare v0.15.5

- deploy/crd/ciskubebenchreports.crd.yaml
- deploy/crd/clustercompliancedetailreports.crd.yaml
- deploy/crd/clustercompliancereports.crd.yaml
- deploy/crd/clusterconfigauditreports.crd.yaml
- deploy/crd/clustervulnerabilityreports.crd.yaml
- deploy/crd/configauditreports.crd.yaml
- deploy/crd/kubehunterreports.crd.yaml
- deploy/crd/vulnerabilityreports.crd.yaml
- deploy/helm/Chart.yaml
- deploy/helm/values.yaml
- deploy/specs/nsa-1.0.yaml
- deploy/static/01-starboard-operator.ns.yaml
- deploy/static/02-starboard-operator.rbac.yaml
- deploy/static/03-starboard-operator.config.yaml
- deploy/static/04-starboard-operator.policies.yaml
- deploy/static/05-starboard-operator.deployment.yaml
- deploy/static/starboard.yaml
- mkdocs.yml
> release: prepare v0.15.6

- README.md
Add what next with trivy live stream recording
> docs(operator): add what next for trivy Q&A

- build/starboard-operator/Dockerfile.ubi8
License is needed in starboard ubi image for Aqua operator
> Adding existing starboard license in ubi image

- .gitignore
- bin/LICENSE
- deploy/crd/ciskubebenchreports.crd.yaml
- deploy/crd/clustercompliancedetailreports.crd.yaml
- deploy/crd/clustercompliancereports.crd.yaml
- deploy/crd/clusterconfigauditreports.crd.yaml
- deploy/crd/clustervulnerabilityreports.crd.yaml
- deploy/crd/configauditreports.crd.yaml
- deploy/crd/kubehunterreports.crd.yaml
- deploy/crd/vulnerabilityreports.crd.yaml
- deploy/helm/Chart.yaml
- deploy/specs/nsa-1.0.yaml
- deploy/static/01-starboard-operator.ns.yaml
- deploy/static/02-starboard-operator.rbac.yaml
- deploy/static/03-starboard-operator.config.yaml
- deploy/static/04-starboard-operator.policies.yaml
- deploy/static/05-starboard-operator.deployment.yaml
- deploy/static/starboard.yaml
- mkdocs.yml
Signed-off-by: Jose Donizetti <jdbjunior@gmail.com>
prepare v0.15.7
> release: prepare v0.15.7

- .goreleaser.yaml
Signed-off-by: Jose Donizetti <jdbjunior@gmail.com>
Fix gorelease due to change https://github.com/aquasecurity/starboard/pull/1238
> fix: fix goreleaser to include LICENSE

- build/starboard-operator/Dockerfile.ubi8
Updating license to correct location in ubi image
@josedonizetti please review
> Updating license to correct location in ubi image

- build/starboard-operator/Dockerfile.ubi8
- deploy/crd/ciskubebenchreports.crd.yaml
- deploy/crd/clustercompliancedetailreports.crd.yaml
- deploy/crd/clustercompliancereports.crd.yaml
- deploy/crd/clusterconfigauditreports.crd.yaml
- deploy/crd/clustervulnerabilityreports.crd.yaml
- deploy/crd/configauditreports.crd.yaml
- deploy/crd/kubehunterreports.crd.yaml
- deploy/crd/vulnerabilityreports.crd.yaml
- deploy/helm/Chart.yaml
- deploy/specs/nsa-1.0.yaml
- deploy/static/01-starboard-operator.ns.yaml
- deploy/static/02-starboard-operator.rbac.yaml
- deploy/static/03-starboard-operator.config.yaml
- deploy/static/04-starboard-operator.policies.yaml
- deploy/static/05-starboard-operator.deployment.yaml
- deploy/static/starboard.yaml
- mkdocs.yml
Signed-off-by: Jose Donizetti <jdbjunior@gmail.com>
prepare v0.15.8
> release: prepare v0.15.8

- build/starboard-operator/Dockerfile.ubi8
- deploy/crd/ciskubebenchreports.crd.yaml
- deploy/crd/clustercompliancedetailreports.crd.yaml
- deploy/crd/clustercompliancereports.crd.yaml
- deploy/crd/clusterconfigauditreports.crd.yaml
- deploy/crd/clustervulnerabilityreports.crd.yaml
- deploy/crd/configauditreports.crd.yaml
- deploy/crd/kubehunterreports.crd.yaml
- deploy/crd/vulnerabilityreports.crd.yaml
- deploy/helm/Chart.yaml
- deploy/specs/nsa-1.0.yaml
- deploy/static/01-starboard-operator.ns.yaml
- deploy/static/02-starboard-operator.rbac.yaml
- deploy/static/03-starboard-operator.config.yaml
- deploy/static/04-starboard-operator.policies.yaml
- deploy/static/05-starboard-operator.deployment.yaml
- deploy/static/starboard.yaml
- mkdocs.yml
> release: prepare v0.15.9-rc

- build/starboard-operator/Dockerfile.ubi8
- deploy/crd/ciskubebenchreports.crd.yaml
- deploy/crd/clustercompliancedetailreports.crd.yaml
- deploy/crd/clustercompliancereports.crd.yaml
- deploy/crd/clusterconfigauditreports.crd.yaml
- deploy/crd/clustervulnerabilityreports.crd.yaml
- deploy/crd/configauditreports.crd.yaml
- deploy/crd/kubehunterreports.crd.yaml
- deploy/crd/vulnerabilityreports.crd.yaml
- deploy/helm/Chart.yaml
- deploy/specs/nsa-1.0.yaml
- deploy/static/01-starboard-operator.ns.yaml
- deploy/static/02-starboard-operator.rbac.yaml
- deploy/static/03-starboard-operator.config.yaml
- deploy/static/04-starboard-operator.policies.yaml
- deploy/static/05-starboard-operator.deployment.yaml
- deploy/static/starboard.yaml
> release: prepare v0.15.9-rc2

- .github/workflows/release.yaml
- build/starboard-operator/Dockerfile.ubi8
- deploy/crd/ciskubebenchreports.crd.yaml
- deploy/crd/clustercompliancedetailreports.crd.yaml
- deploy/crd/clustercompliancereports.crd.yaml
- deploy/crd/clusterconfigauditreports.crd.yaml
- deploy/crd/clustervulnerabilityreports.crd.yaml
- deploy/crd/configauditreports.crd.yaml
- deploy/crd/kubehunterreports.crd.yaml
- deploy/crd/vulnerabilityreports.crd.yaml
- deploy/helm/Chart.yaml
- deploy/specs/nsa-1.0.yaml
- deploy/static/01-starboard-operator.ns.yaml
- deploy/static/02-starboard-operator.rbac.yaml
- deploy/static/03-starboard-operator.config.yaml
- deploy/static/04-starboard-operator.policies.yaml
- deploy/static/05-starboard-operator.deployment.yaml
- deploy/static/starboard.yaml
> release: prepare v0.15.9-rc3

- build/starboard-operator/Dockerfile.ubi8
- deploy/crd/ciskubebenchreports.crd.yaml
- deploy/crd/clustercompliancedetailreports.crd.yaml
- deploy/crd/clustercompliancereports.crd.yaml
- deploy/crd/clusterconfigauditreports.crd.yaml
- deploy/crd/clustervulnerabilityreports.crd.yaml
- deploy/crd/configauditreports.crd.yaml
- deploy/crd/kubehunterreports.crd.yaml
- deploy/crd/vulnerabilityreports.crd.yaml
- deploy/helm/Chart.yaml
- deploy/specs/nsa-1.0.yaml
- deploy/static/01-starboard-operator.ns.yaml
- deploy/static/02-starboard-operator.rbac.yaml
- deploy/static/03-starboard-operator.config.yaml
- deploy/static/04-starboard-operator.policies.yaml
- deploy/static/05-starboard-operator.deployment.yaml
- deploy/static/starboard.yaml
> release: prepare v0.15.9

- build/starboard-operator/Dockerfile
- build/starboard/Dockerfile
> chore: upgrade alpine v3.16.2

- .github/workflows/release-snapshot.yaml
> chore: disable aqua image scanning

- build/starboard-operator/Dockerfile.ubi8
- deploy/crd/ciskubebenchreports.crd.yaml
- deploy/crd/clustercompliancedetailreports.crd.yaml
- deploy/crd/clustercompliancereports.crd.yaml
- deploy/crd/clusterconfigauditreports.crd.yaml
- deploy/crd/clustervulnerabilityreports.crd.yaml
- deploy/crd/configauditreports.crd.yaml
- deploy/crd/kubehunterreports.crd.yaml
- deploy/crd/vulnerabilityreports.crd.yaml
- deploy/helm/Chart.yaml
- deploy/specs/nsa-1.0.yaml
- deploy/static/01-starboard-operator.ns.yaml
- deploy/static/02-starboard-operator.rbac.yaml
- deploy/static/03-starboard-operator.config.yaml
- deploy/static/04-starboard-operator.policies.yaml
- deploy/static/05-starboard-operator.deployment.yaml
- deploy/static/starboard.yaml
- mkdocs.yml
> release: prepare v0.15.10

- .github/workflows/release-snapshot.yaml
add team notification on vulnerabilities found
> chore: add team notification on vulnerabilities found

- build/starboard-operator/Dockerfile.ubi8
- deploy/crd/ciskubebenchreports.crd.yaml
- deploy/crd/clustercompliancedetailreports.crd.yaml
- deploy/crd/clustercompliancereports.crd.yaml
- deploy/crd/clusterconfigauditreports.crd.yaml
- deploy/crd/clustervulnerabilityreports.crd.yaml
- deploy/crd/configauditreports.crd.yaml
- deploy/crd/kubehunterreports.crd.yaml
- deploy/crd/vulnerabilityreports.crd.yaml
- deploy/helm/Chart.yaml
- deploy/specs/nsa-1.0.yaml
- deploy/static/01-starboard-operator.ns.yaml
- deploy/static/02-starboard-operator.rbac.yaml
- deploy/static/03-starboard-operator.config.yaml
- deploy/static/04-starboard-operator.policies.yaml
- deploy/static/05-starboard-operator.deployment.yaml
- deploy/static/starboard.yaml
- mkdocs.yml
> release: prepare v0.15.11

- build/starboard-operator/Dockerfile.ubi8
- deploy/crd/ciskubebenchreports.crd.yaml
- deploy/crd/clustercompliancedetailreports.crd.yaml
- deploy/crd/clustercompliancereports.crd.yaml
- deploy/crd/clusterconfigauditreports.crd.yaml
- deploy/crd/clustervulnerabilityreports.crd.yaml
- deploy/crd/configauditreports.crd.yaml
- deploy/crd/kubehunterreports.crd.yaml
- deploy/crd/vulnerabilityreports.crd.yaml
- deploy/helm/Chart.yaml
- deploy/specs/nsa-1.0.yaml
- deploy/static/01-starboard-operator.ns.yaml
- deploy/static/02-starboard-operator.rbac.yaml
- deploy/static/03-starboard-operator.config.yaml
- deploy/static/04-starboard-operator.policies.yaml
- deploy/static/05-starboard-operator.deployment.yaml
- deploy/static/starboard.yaml
- mkdocs.yml
> release: prepare v0.15.12-rc

- build/starboard-operator/Dockerfile.ubi8
- deploy/crd/ciskubebenchreports.crd.yaml
- deploy/crd/clustercompliancedetailreports.crd.yaml
- deploy/crd/clustercompliancereports.crd.yaml
- deploy/crd/clusterconfigauditreports.crd.yaml
- deploy/crd/clustervulnerabilityreports.crd.yaml
- deploy/crd/configauditreports.crd.yaml
- deploy/crd/kubehunterreports.crd.yaml
- deploy/crd/vulnerabilityreports.crd.yaml
- deploy/helm/Chart.yaml
- deploy/specs/nsa-1.0.yaml
- deploy/static/01-starboard-operator.ns.yaml
- deploy/static/02-starboard-operator.rbac.yaml
- deploy/static/03-starboard-operator.config.yaml
- deploy/static/04-starboard-operator.policies.yaml
- deploy/static/05-starboard-operator.deployment.yaml
- deploy/static/starboard.yaml
- mkdocs.yml
> release: prepare v0.15.13

- .github/workflows/release-snapshot.yaml
- .github/workflows/release.yaml
> chore: bump go version release 1.19

- build/starboard-operator/Dockerfile.fips.ubi8
- build/starboard-operator/Dockerfile.ubi8
- deploy/crd/ciskubebenchreports.crd.yaml
- deploy/crd/clustercompliancedetailreports.crd.yaml
- deploy/crd/clustercompliancereports.crd.yaml
- deploy/crd/clusterconfigauditreports.crd.yaml
- deploy/crd/clustervulnerabilityreports.crd.yaml
- deploy/crd/configauditreports.crd.yaml
- deploy/crd/kubehunterreports.crd.yaml
- deploy/crd/vulnerabilityreports.crd.yaml
- deploy/helm/Chart.yaml
- deploy/specs/nsa-1.0.yaml
- deploy/static/01-starboard-operator.ns.yaml
- deploy/static/02-starboard-operator.rbac.yaml
- deploy/static/03-starboard-operator.config.yaml
- deploy/static/04-starboard-operator.policies.yaml
- deploy/static/05-starboard-operator.deployment.yaml
- deploy/static/starboard.yaml
- mkdocs.yml
> release: prepare v0.15.14

- build/starboard-operator/Dockerfile.fips.ubi8
- build/starboard-operator/Dockerfile.ubi8
- deploy/crd/ciskubebenchreports.crd.yaml
- deploy/crd/clustercompliancedetailreports.crd.yaml
- deploy/crd/clustercompliancereports.crd.yaml
- deploy/crd/clusterconfigauditreports.crd.yaml
- deploy/crd/clustervulnerabilityreports.crd.yaml
- deploy/crd/configauditreports.crd.yaml
- deploy/crd/kubehunterreports.crd.yaml
- deploy/crd/vulnerabilityreports.crd.yaml
- deploy/helm/Chart.yaml
- deploy/specs/nsa-1.0.yaml
- deploy/static/01-starboard-operator.ns.yaml
- deploy/static/02-starboard-operator.rbac.yaml
- deploy/static/03-starboard-operator.config.yaml
- deploy/static/04-starboard-operator.policies.yaml
- deploy/static/05-starboard-operator.deployment.yaml
- deploy/static/starboard.yaml
- mkdocs.yml
> release: prepare v0.15.16-rc

- build/starboard-operator/Dockerfile.fips.ubi8
- build/starboard-operator/Dockerfile.ubi8
- deploy/crd/ciskubebenchreports.crd.yaml
- deploy/crd/clustercompliancedetailreports.crd.yaml
- deploy/crd/clustercompliancereports.crd.yaml
- deploy/crd/clusterconfigauditreports.crd.yaml
- deploy/crd/clustervulnerabilityreports.crd.yaml
- deploy/crd/configauditreports.crd.yaml
- deploy/crd/kubehunterreports.crd.yaml
- deploy/crd/vulnerabilityreports.crd.yaml
- deploy/helm/Chart.yaml
- deploy/specs/nsa-1.0.yaml
- deploy/static/01-starboard-operator.ns.yaml
- deploy/static/02-starboard-operator.rbac.yaml
- deploy/static/03-starboard-operator.config.yaml
- deploy/static/04-starboard-operator.policies.yaml
- deploy/static/05-starboard-operator.deployment.yaml
- deploy/static/starboard.yaml
- mkdocs.yml
> release: prepare v0.15.16

- build/starboard-operator/Dockerfile.fips.ubi8
- build/starboard-operator/Dockerfile.ubi8
- deploy/crd/ciskubebenchreports.crd.yaml
- deploy/crd/clustercompliancedetailreports.crd.yaml
- deploy/crd/clustercompliancereports.crd.yaml
- deploy/crd/clusterconfigauditreports.crd.yaml
- deploy/crd/clustervulnerabilityreports.crd.yaml
- deploy/crd/configauditreports.crd.yaml
- deploy/crd/kubehunterreports.crd.yaml
- deploy/crd/vulnerabilityreports.crd.yaml
- deploy/helm/Chart.yaml
- deploy/specs/nsa-1.0.yaml
- deploy/static/01-starboard-operator.ns.yaml
- deploy/static/02-starboard-operator.rbac.yaml
- deploy/static/03-starboard-operator.config.yaml
- deploy/static/04-starboard-operator.policies.yaml
- deploy/static/05-starboard-operator.deployment.yaml
- deploy/static/starboard.yaml
- mkdocs.yml
> release: prepare-v0.15.17

- go.mod
- go.sum
with this fix we will be resolving the vulnerabilities by upgrading the packages in the latest starboard version 0.15.17
> Fix security vulnerabilities in starboard:0.15.17

- build/starboard-operator/Dockerfile.fips.ubi8
- build/starboard-operator/Dockerfile.ubi8
- deploy/crd/ciskubebenchreports.crd.yaml
- deploy/crd/clustercompliancedetailreports.crd.yaml
- deploy/crd/clustercompliancereports.crd.yaml
- deploy/crd/clusterconfigauditreports.crd.yaml
- deploy/crd/clustervulnerabilityreports.crd.yaml
- deploy/crd/configauditreports.crd.yaml
- deploy/crd/kubehunterreports.crd.yaml
- deploy/crd/vulnerabilityreports.crd.yaml
- deploy/helm/Chart.yaml
- deploy/specs/nsa-1.0.yaml
- deploy/static/01-starboard-operator.ns.yaml
- deploy/static/02-starboard-operator.rbac.yaml
- deploy/static/03-starboard-operator.config.yaml
- deploy/static/04-starboard-operator.policies.yaml
- deploy/static/05-starboard-operator.deployment.yaml
- deploy/static/starboard.yaml
- mkdocs.yml
> release: prepare v0.15.18

- build/starboard-operator/Dockerfile.fips.ubi8
- build/starboard-operator/Dockerfile.ubi8
- deploy/crd/ciskubebenchreports.crd.yaml
- deploy/crd/clustercompliancedetailreports.crd.yaml
- deploy/crd/clustercompliancereports.crd.yaml
- deploy/crd/clusterconfigauditreports.crd.yaml
- deploy/crd/clustervulnerabilityreports.crd.yaml
- deploy/crd/configauditreports.crd.yaml
- deploy/crd/kubehunterreports.crd.yaml
- deploy/crd/vulnerabilityreports.crd.yaml
- deploy/helm/Chart.yaml
- deploy/specs/nsa-1.0.yaml
- deploy/static/01-starboard-operator.ns.yaml
- deploy/static/02-starboard-operator.rbac.yaml
- deploy/static/03-starboard-operator.config.yaml
- deploy/static/04-starboard-operator.policies.yaml
- deploy/static/05-starboard-operator.deployment.yaml
- deploy/static/starboard.yaml
- mkdocs.yml
> release: prepare v0.15.19

- build/starboard-operator/Dockerfile.fips.ubi8
- build/starboard-operator/Dockerfile.fips.ubi9
- build/starboard-operator/Dockerfile.ubi8
- build/starboard-operator/Dockerfile.ubi9
- deploy/crd/ciskubebenchreports.crd.yaml
- deploy/crd/clustercompliancedetailreports.crd.yaml
- deploy/crd/clustercompliancereports.crd.yaml
- deploy/crd/clusterconfigauditreports.crd.yaml
- deploy/crd/clustervulnerabilityreports.crd.yaml
- deploy/crd/configauditreports.crd.yaml
- deploy/crd/kubehunterreports.crd.yaml
- deploy/crd/vulnerabilityreports.crd.yaml
- deploy/helm/Chart.yaml
- deploy/specs/nsa-1.0.yaml
- deploy/static/01-starboard-operator.ns.yaml
- deploy/static/02-starboard-operator.rbac.yaml
- deploy/static/03-starboard-operator.config.yaml
- deploy/static/04-starboard-operator.policies.yaml
- deploy/static/05-starboard-operator.deployment.yaml
- deploy/static/starboard.yaml
- mkdocs.yml
> release: prepare v0.15.20

- .github/workflows/release.yaml
chore: remove release pipeline cache
> chore: remove release pipeline cache

- .github/workflows/release.yaml
> chore: remove cleanup action

- .goreleaser.yaml
> fix: failure in goreleaser

- build/starboard-operator/Dockerfile.fips.ubi8
- build/starboard-operator/Dockerfile.fips.ubi9
- build/starboard-operator/Dockerfile.ubi8
- build/starboard-operator/Dockerfile.ubi9
- deploy/crd/ciskubebenchreports.crd.yaml
- deploy/crd/clustercompliancedetailreports.crd.yaml
- deploy/crd/clustercompliancereports.crd.yaml
- deploy/crd/clusterconfigauditreports.crd.yaml
- deploy/crd/clustervulnerabilityreports.crd.yaml
- deploy/crd/configauditreports.crd.yaml
- deploy/crd/kubehunterreports.crd.yaml
- deploy/crd/vulnerabilityreports.crd.yaml
- deploy/helm/Chart.yaml
- deploy/specs/nsa-1.0.yaml
- deploy/static/01-starboard-operator.ns.yaml
- deploy/static/02-starboard-operator.rbac.yaml
- deploy/static/03-starboard-operator.config.yaml
- deploy/static/04-starboard-operator.policies.yaml
- deploy/static/05-starboard-operator.deployment.yaml
- deploy/static/starboard.yaml
- mkdocs.yml
> release: prepare v0.15.21

- build/starboard-operator/Dockerfile.fips.ubi8
- build/starboard-operator/Dockerfile.fips.ubi9
- build/starboard-operator/Dockerfile.ubi8
- build/starboard-operator/Dockerfile.ubi9
- deploy/crd/ciskubebenchreports.crd.yaml
- deploy/crd/clustercompliancedetailreports.crd.yaml
- deploy/crd/clustercompliancereports.crd.yaml
- deploy/crd/clusterconfigauditreports.crd.yaml
- deploy/crd/clustervulnerabilityreports.crd.yaml
- deploy/crd/configauditreports.crd.yaml
- deploy/crd/kubehunterreports.crd.yaml
- deploy/crd/vulnerabilityreports.crd.yaml
- deploy/helm/Chart.yaml
- deploy/specs/nsa-1.0.yaml
- deploy/static/01-starboard-operator.ns.yaml
- deploy/static/02-starboard-operator.rbac.yaml
- deploy/static/03-starboard-operator.config.yaml
- deploy/static/04-starboard-operator.policies.yaml
- deploy/static/05-starboard-operator.deployment.yaml
- deploy/static/starboard.yaml
- mkdocs.yml
> release: prepare v0.15.22

- .github/workflows/release.yaml
- .goreleaser.yaml
- Makefile
> No Disc space error fix.

- build/starboard-operator/Dockerfile.fips.ubi8
- build/starboard-operator/Dockerfile.fips.ubi9
- build/starboard-operator/Dockerfile.ubi8
- build/starboard-operator/Dockerfile.ubi9
- deploy/crd/ciskubebenchreports.crd.yaml
- deploy/crd/clustercompliancedetailreports.crd.yaml
- deploy/crd/clustercompliancereports.crd.yaml
- deploy/crd/clusterconfigauditreports.crd.yaml
- deploy/crd/clustervulnerabilityreports.crd.yaml
- deploy/crd/configauditreports.crd.yaml
- deploy/crd/kubehunterreports.crd.yaml
- deploy/crd/vulnerabilityreports.crd.yaml
- deploy/helm/Chart.yaml
- deploy/specs/nsa-1.0.yaml
- deploy/static/01-starboard-operator.ns.yaml
- deploy/static/02-starboard-operator.rbac.yaml
- deploy/static/03-starboard-operator.config.yaml
- deploy/static/04-starboard-operator.policies.yaml
- deploy/static/05-starboard-operator.deployment.yaml
- deploy/static/starboard.yaml
- mkdocs.yml
release: prepare v0.15.23
- Close #XXX
Remove this section if you don't have related PRs.
> release: prepare v0.15.23

- build/starboard-operator/Dockerfile.fips.ubi8
- build/starboard-operator/Dockerfile.fips.ubi9
- build/starboard-operator/Dockerfile.ubi8
- build/starboard-operator/Dockerfile.ubi9
- deploy/crd/ciskubebenchreports.crd.yaml
- deploy/crd/clustercompliancedetailreports.crd.yaml
- deploy/crd/clustercompliancereports.crd.yaml
- deploy/crd/clusterconfigauditreports.crd.yaml
- deploy/crd/clustervulnerabilityreports.crd.yaml
- deploy/crd/configauditreports.crd.yaml
- deploy/crd/kubehunterreports.crd.yaml
- deploy/crd/vulnerabilityreports.crd.yaml
- deploy/helm/Chart.yaml
- deploy/specs/nsa-1.0.yaml
- deploy/static/01-starboard-operator.ns.yaml
- deploy/static/02-starboard-operator.rbac.yaml
- deploy/static/03-starboard-operator.config.yaml
- deploy/static/04-starboard-operator.policies.yaml
- deploy/static/05-starboard-operator.deployment.yaml
- deploy/static/starboard.yaml
- mkdocs.yml
> release: prepare v0.15.24

- build/starboard-operator/Dockerfile.ubi9
fix: ERROR: failed to solve: dockerfile parse error on line 17: unknown instruction: ̰
> fix: dockerfile parse error.

- .github/workflows/release.yaml
- .goreleaser.yaml
- Close #XXX
Remove this section if you don't have related PRs.
> Lihiz release

- build/starboard-operator/Dockerfile.fips.ubi8
- build/starboard-operator/Dockerfile.fips.ubi9
- build/starboard-operator/Dockerfile.ubi8
- build/starboard-operator/Dockerfile.ubi9
- deploy/crd/ciskubebenchreports.crd.yaml
- deploy/crd/clustercompliancedetailreports.crd.yaml
- deploy/crd/clustercompliancereports.crd.yaml
- deploy/crd/clusterconfigauditreports.crd.yaml
- deploy/crd/clustervulnerabilityreports.crd.yaml
- deploy/crd/configauditreports.crd.yaml
- deploy/crd/kubehunterreports.crd.yaml
- deploy/crd/vulnerabilityreports.crd.yaml
- deploy/helm/Chart.yaml
- deploy/specs/nsa-1.0.yaml
- deploy/static/01-starboard-operator.ns.yaml
- deploy/static/02-starboard-operator.rbac.yaml
- deploy/static/03-starboard-operator.config.yaml
- deploy/static/04-starboard-operator.policies.yaml
- deploy/static/05-starboard-operator.deployment.yaml
- deploy/static/starboard.yaml
- mkdocs.yml
> release: prepare v0.15.25

- build/starboard-operator/Dockerfile.fips.ubi8
- build/starboard-operator/Dockerfile.fips.ubi9
- build/starboard-operator/Dockerfile.ubi8
- build/starboard-operator/Dockerfile.ubi9
- deploy/crd/ciskubebenchreports.crd.yaml
- deploy/crd/clustercompliancedetailreports.crd.yaml
- deploy/crd/clustercompliancereports.crd.yaml
- deploy/crd/clusterconfigauditreports.crd.yaml
- deploy/crd/clustervulnerabilityreports.crd.yaml
- deploy/crd/configauditreports.crd.yaml
- deploy/crd/kubehunterreports.crd.yaml
- deploy/crd/vulnerabilityreports.crd.yaml
- deploy/helm/Chart.yaml
- deploy/specs/nsa-1.0.yaml
- deploy/static/01-starboard-operator.ns.yaml
- deploy/static/02-starboard-operator.rbac.yaml
- deploy/static/03-starboard-operator.config.yaml
- deploy/static/04-starboard-operator.policies.yaml
- deploy/static/05-starboard-operator.deployment.yaml
- deploy/static/starboard.yaml
- mkdocs.yml
> release: prepare v0.15.26
