.github/workflows/build.yaml, .goreleaser.yaml, kube/examples/configauditreports.yaml, kube/examples/vulnerabilities.yaml
=> docs(examples): Add configauditreports example YAML

pkg/cmd/commands.go, pkg/cmd/find_vulnerabilities.go, pkg/cmd/kube_bench.go, pkg/cmd/kube_hunter.go, pkg/cmd/polaris.go, pkg/cmd/root.go, pkg/find/vulnerabilities/scanner.go, pkg/find/vulnerabilities/trivy/scanner.go, pkg/kube/workload.go, pkg/kubebench/scanner.go, pkg/kubehunter/scanner.go, pkg/polaris/scanner.go, pkg/runner/runner.go, pkg/scanners/base.go, pkg/scanners/base_test.go
=> feat: Allow specifying timeout for scan jobs

pkg/cmd/commands.go, pkg/find/vulnerabilities/trivy/converter.go, pkg/find/vulnerabilities/trivy/converter_test.go, pkg/find/vulnerabilities/trivy/scanner.go, pkg/find/vulnerabilities/writer.go, pkg/kube/pod/manager.go, pkg/kube/workload.go, pkg/kubebench/scanner.go, pkg/kubehunter/scanner.go, pkg/polaris/scanner.go
Resolves: #52
This PR leverages container termination messages to get insights into failing scan jobs: https://kubernetes.io/docs/tasks/debug-application-cluster/determine-reason-pod-failure/
For example, if a scan Job for finding vulnerabilities fails, we can see what was the root cause by checking the last state of the underlying Pod created by the scan Job:
```
$ k starboard find vuln deploy/nginx-ko --delete-scan-job=false -v 3
```
```
$ k get pod -n starboard <pod name> -o yaml
```
```yaml
containerStatuses:
- containerID: docker://ff811ff415b4d8bda909a61a5088b309fb43025eadea7d09fd2acc58ad2e72dd
image: aquasec/trivy:0.9.1
imageID: docker-pullable://aquasec/trivy@sha256:5020dac24a63ef4f24452a0c63ebbfe93a5309e40f6353d1ee8221d2184ee954
lastState: {}
name: nginx
ready: false …
```
=> fix: Get error message from failing scan job

pkg/find/vulnerabilities/trivy/converter.go, pkg/find/vulnerabilities/trivy/converter_test.go
=> fix(trivy): Parse output of scanning scratch images

.github/workflows/build.yaml, .github/workflows/release.yaml
The latest release of GoReleaser has broken the way we auto generate changes log. Therefore:
- I pinned to GoReleaser v0.138.0
- Updated GitHub Action config
=> chore: Update GoReleaser Action config

kube/crd/vulnerabilities-crd.yaml, pkg/find/vulnerabilities/scanner.go, pkg/find/vulnerabilities/trivy/scanner.go
The idea of such interface is to reuse code in starboard security operator for:
- Preparing the descriptor of a Trivy scan job
- Parsing the output logs of the Trivy scan job to convert the JSON output to instances of the vulnerabilities.aquasecurity.github.io resources
**Note:** You can see the client code of such interface in the draft PR https://github.com/aquasecurity/starboard-security-operator/pull/8
=> refactor: Define interface for async Trivy scanner

pkg/cmd/find_vulnerabilities.go, pkg/docker/config.go, pkg/docker/config_test.go, pkg/find/vulnerabilities/crd/writer.go, pkg/find/vulnerabilities/crd/writer_test.go, pkg/find/vulnerabilities/writer.go
=> feat(api): Add method for getting vulnerability reports by the specified workload

pkg/kube/cr_manager.go, pkg/polaris/scanner.go
Up until now we used an old tagged version of Polaris.
This PR updates the polaris release tag to **1.1.0**
Changes made to support the new version:
- Now explicitly specifying the audit config file in the command line.
- Changed the audit config file to an updated default version. (some old values were no longer supported)
related #33
=> Update polaris to 1.1.0

cmd/starboard/main.go
The Error handling was done via `fmt.Printf()`
This PR changes this to use the `fmt.Fprintf(os.Stderr)`
=> Fix: Command errors now go to stderr

kube/crd/vulnerabilities-crd.yaml
If we add additional printer columns to CRD, we can have the following output:
```
$ kubectl get vulnerabilities
NAME                                   REPOSITORY   TAG    SCANNER
ddbb8bfb-040a-42a1-a051-d5aff77a53e7   nginx        1.16   Trivy
```
```
$ kubectl get vulnerabilities -o wide
NAME                                   REPOSITORY   TAG    SCANNER   CRITICAL   HIGH   MEDIUM   LOW   UNKNOWN
ddbb8bfb-040a-42a1-a051-d5aff77a53e7   nginx        1.16   Trivy     0          0      27       92    3
```
=> feat: Define additional printer colums for vulnerabilities resource

.github/workflows/build.yaml, .github/workflows/release.yaml, Makefile, go.mod, hack/tools.go, integration-tests/starboard_integration_suite_test.go, integration-tests/starboard_integration_test.go, pkg/polaris/scanner.go
In this PR I'd like to introduce:
- https://github.com/onsi/ginkgo - BDD testing framework for Go (good for integration / component / e2e tests; might be overkill for unit tests)
- https://github.com/onsi/gomega - BDD matchers library
- https://github.com/engineerd/setup-kind - GitHub Action to run Kubernetes in Docker cluster
The Gomega has great support for [Asynch Assertions](http://onsi.github.io/gomega/#making-asynchronous-assertions), which is even more relevant for integration testing reconciliation loops, e.g. asserting on desired vs expected / actual state of the world
=> test(integration): Add scaffold for running integration tests

.github/workflows/codeql-analysis.yml
=> chore: Tune CodeQL config

pkg/apis/aquasecurity/v1alpha1/cis_kube_bench_types.go, pkg/apis/aquasecurity/v1alpha1/config_audit_types.go, pkg/apis/aquasecurity/v1alpha1/kube_hunter_types.go, pkg/apis/aquasecurity/v1alpha1/vulnerability_types.go, pkg/kube/cr_manager.go
For troubleshooting and to do a proper cleanup even without running the `starbaord cleanup` subcommand
=> feat: Add app.kubernetes.io/managed-by=starboard label to objects created by Starboard

pkg/apis/aquasecurity/v1alpha1/vulnerability_types.go
To have such a nice output:
```
$ kubectl get vulnerabilities
NAME                                   REPOSITORY      TAG    SCANNER
4b53fe18-6808-42c9-a477-d3f3caac73a3   library/nginx   1.16   Trivy
```
```
$ kubectl get vuln -o wide
NAME                                   REPOSITORY      TAG    SCANNER   CRITICAL   HIGH   MEDIUM   LOW   UNKNOWN
4b53fe18-6808-42c9-a477-d3f3caac73a3   library/nginx   1.16   Trivy     0          1      34       93    0
```
=> feat: Define additional printer columns for vulnerability report

cmd/starboard/main_test.go, pkg/cmd/commands.go, pkg/cmd/find.go, pkg/cmd/find_test.go, pkg/cmd/find_vulnerabilities.go, pkg/cmd/find_vulnerabilities_test.go, pkg/cmd/get_report.go, pkg/cmd/kube_bench.go, pkg/find/vulnerabilities/crd/writer.go, pkg/find/vulnerabilities/crd/writer_test.go, pkg/find/vulnerabilities/trivy/scanner.go, pkg/find/vulnerabilities/writer.go, pkg/kube/object.go, pkg/kube/object_test.go, pkg/kube/pod/manager.go, pkg/kubebench/crd/writer.go, pkg/kubebench/crd/writer_test.go
=> feat: Set ownerReference for vulnerabilities resource

pkg/find/vulnerabilities/trivy/scanner.go, pkg/kube/pod/manager.go, pkg/kubebench/scanner.go, pkg/kubehunter/scanner.go, pkg/polaris/scanner.go, pkg/scanners/base.go
=> refactor: Common methods

kube/crd/ciskubebenchreports-crd.yaml, kube/crd/vulnerabilities-crd.yaml, pkg/apis/aquasecurity/v1alpha1/cis_kube_bench_types.go, pkg/apis/aquasecurity/v1alpha1/vulnerability_types.go, pkg/kubebench/converter.go, pkg/kubebench/testdata/goldenMultiple.json, pkg/kubebench/testdata/goldenSingle.json
We could do that for Vulnerability reports. Now we can do the same for CISKubeBenchReports:
```
$ kubectl get vuln -o wide
NAME                                   REPOSITORY      TAG    SCANNER   AGE   CRITICAL   HIGH   MEDIUM   LOW   UNKNOWN
2cec4a5c-ccfa-41ea-856e-87d21650ccc2   library/nginx   1.16   Trivy     11m   0          3      34       94    0
```
```
$ kubectl get kubebench -o wide
NAME                 SCANNER      AGE   PASS   INFO   WARN   FAIL
kind-control-plane   kube-bench   11m   41     0      11     13
```
```
$ kubectl get kubebench -o jsonpath='{.items[*].report.summary.failCount}'
13
```
What's more for frontends, such as Octant or Lens, we don't have to calculate summaries in the plugin code.
Also Octant can display additional columns even if we don't install our …
=> feat: Add summary and printer columns to CISKubeBenchReports

.github/workflows/release.yaml, .goreleaser.yaml, Dockerfile
Some folks find it useful to have `docker.io/aquasec/starboard` image available from a public registry such as DockerHub, e.g. see #54 
I tested it locally with:
```
$ goreleaser release --snapshot --rm-dist --skip-publish
$ docker run --rm docker.io/aquasec/starboard:924389a5ad7037646eeb7a37ade05494d75a85ba
```
=> chore: Publish Docker images to DockerHub on release

README.md, pkg/find/vulnerabilities/trivy/scanner.go
Some people might run their (dev) clusters behind the proxy.
It is possible to set the HTTP_PROXY environment variable
when using Trivy directly. This commit makes it possible
to use Starboard CLI and pass HTTP proxy config to Trivy by
setting the trivy.httpProxy configuration parameter before
you run the starboard find vulnerabilities command.
$ starboard init
$ kubectl patch configmap starboard -n starboard \
--type merge \
-p '{"data": {"trivy.httpProxy":"http://your-proxy:9001"}}'
$ starboard find vulnerabilities deploy/my-deployment
Resolves: #84
=> feat(find vulnerabilities): Configure HTTP proxy for Trivy

pkg/apis/aquasecurity/v1alpha1/config_audit_types.go, pkg/apis/aquasecurity/v1alpha1/kube_hunter_types.go, pkg/kubehunter/model.go, pkg/polaris/converter.go
This PR adds additional printer columns to show summary for ConfigAudits and KubeHunter reports. (like already implemented for vulnerabilities reports)
```bash
$ k get configaudit -o wide                                        
NAME                          SCANNER   AGE     DANGER   WARNING
deployment.nginx-deployment   Polaris   6m31s   0        16
```
```bash
$ k get kubehunter -o wide    
NAME      SCANNER       AGE   HIGH   MEDIUM   LOW
cluster   kube-hunter   3s    1      1        1
```
Closes #149 
Closes #148
=> Added Summary Columns for ConfigAudits and KubeHunter Reports

pkg/cmd/init.go
Updated init to include a long message to properly explain the init
process.
Note: The wording has been gleaned from the readme, but might need
adjusting.
Resolves aquasecurity/starboard#164
Signed-off-by: Shaun McLernon <shaun@codesome.tech>
=> feat: Add long message shown in 'starboard help init' output

pkg/cmd/config.go, pkg/cmd/config_test.go, pkg/cmd/root.go
Added a `starboard config` command, with `--get` and `--name-only` local flags: 
The plain `starboard config` command is equivalent to the kubectl alternative - `kubectl describe configmap --namespace=starboard`
```
$ starboard config
trivy.severity
UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
polaris.config.yaml
checks:
multipleReplicasForDeployment: ignore
priorityClassNotSet: ignore
...
```
Adding the `--get` flag returns the values associated with the specified key
```
$ starboard config --get trivy.severity
UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
```
Including `--name-only` returns just the names (keys) in the config map
```
$ starboard config --name-only
polaris.config.yaml
trivy.severity
```
In the case where a user includes both flags, `--name-only` is ignored.
=> feat: adding new config command with get and name-only local flags

Dockerfile.starboard-scanner-aqua, cmd/starboard-operator/main.go, cmd/starboard-scanner-aqua/main.go, deploy/operator/examples/starboard-scanner-aqua.job.yaml, pkg/operator/aqua/scanner.go, pkg/operator/aqua/scanner/api/scanner.go, pkg/operator/aqua/scanner/cli/scanner.go, pkg/operator/etc/config.go
=> fix: Pass Aqua version to the scanner

Dockerfile.starboard-scanner-aqua
Alpine 3.9 is becoming EOL as of 1st of November 2021. Alpine 3.12 is the latest release of Alpine
=> Chore: bump up alpine to 3.12

README.md
As I was going through the getting started section for #175 , I thought it would be helpful to have the step to create the `dev` namespace.
I also fixed toc as kubectl plugin is not related to installing from binary release.
=> Added instructions to create dev namespace to Getting Started section.

cmd/starboard-operator/main.go, deploy/helm/templates/rbac.yaml, deploy/kubectl/03-starboard-operator.clusterrole.yaml, pkg/cmd/cleanup.go, pkg/cmd/config.go, pkg/cmd/find_vulnerabilities.go, pkg/cmd/init.go, pkg/cmd/kube_bench.go, pkg/ext/id_generator.go, pkg/find/vulnerabilities/scanner.go, pkg/find/vulnerabilities/trivy/scanner.go, pkg/kube/cr_manager.go, pkg/kube/runnable_job.go, pkg/kubebench/converter_test.go, pkg/kubehunter/model.go, pkg/operator/etc/config.go, pkg/operator/trivy/scanner.go, pkg/starboard/config.go, pkg/starboard/config_test.go
=> feat(operator): Allow configuring scanners

pkg/cmd/get.go, pkg/cmd/get_vulnerabilities.go, pkg/cmd/root.go
Fixes https://github.com/aquasecurity/starboard/issues/142
=> refactor: Refactor get vulnerabilities command to use client instead of kubectl

pkg/cmd/get.go, pkg/cmd/get_configaudit.go
The purpose is to solve the problem described in #142 but for configaudit.
Technically, this is similar to #193
=> refactor: Refactor get configaudit command to use client instead of kubectl

pkg/cmd/get_configaudit.go, pkg/cmd/get_report.go, pkg/cmd/get_vulnerabilities.go, pkg/polaris/crd/writer.go, pkg/polaris/writer.go, pkg/report/html.go, pkg/report/report.go, pkg/report/templates/default.qtpl, pkg/report/templates/default.qtpl.go, pkg/vulnerabilityreport/store.go, pkg/vulnerabilityreport/store_test.go, pkg/vulnerabilityreport/writer.go, pkg/vulnerabilityreport/writer_test.go
=> refactor: Find VulnerabilityReports by owner

pkg/cmd/root.go, pkg/cmd/scan.go, pkg/cmd/scan_ciskubebench.go, pkg/cmd/scan_configaudit.go, pkg/cmd/scan_kubehunter.go, pkg/cmd/scan_vulnerabilities.go
The currently used find verb is not intuitive for everyone and can be confusing:
`kubectl starboard find vuln deploy/my-deploy -n my-namespace`
`kubectl starboard find risks deploy/my-deploy -n my-namespace`
In the name of consistency and to follow this `kubectl starboard <verb> <scanner>` pattern
`kubectl starboard find vulnerabilities`
`kubectl starboard polaris`
`kubectl starboard kube-bench`
`kubectl starboard kube-hunter`
was changed to
`kubectl starboard find vulnerabilities` with alias `kubectl starbaord trivy`
`kubectl starboard audit configuration` with alias `kubectl starbaord polaris`
`kubectl starboard run kube-bench` with alias `kubectl starboard kube-bench`
`kubectl starboard run kube-hunter` with alias `kubectl starboard kube-hunter`
closes #21
=> refactor: Make cli verbs uniform and include scanner aliases

README.md, deploy/init/03-starboard.cm.yaml, deploy/trivy-server/03-trivy-server.deployment.yaml, deploy/trivy-server/README.md, itest/starboard/starboard_cli_test.go, pkg/find/vulnerabilities/scanner.go, pkg/starboard/config.go, pkg/starboard/config_test.go, pkg/trivy/converter.go, pkg/trivy/converter_test.go, pkg/trivy/model.go, pkg/trivy/scanner.go
=> feat(vulnerabilityreports): Use primary URLs returned by Trivy v0.14.0

itest/starboard/starboard_cli_test.go, pkg/cmd/cleanup.go, pkg/cmd/config.go, pkg/cmd/init.go, pkg/kube/cr_manager.go, pkg/starboard/config.go, pkg/starboard/config_test.go, pkg/starboard/constants.go, pkg/trivy/scanner.go
The init command creates the starboard ConfigMap in the starboard namespace.
This is not suitable for setting sensitive params such as tokens or passwords.
=> feat(config): Add starboard secret to store sensitive config params

Makefile
Use docker to preview MkDocs site without installing it on your laptop:
```
$ make mkdocs-serve && open http://localhost:8080
```
```
$ make mkdocs-serve MKDOCS_PORT=9090 && open http://localhost:9090
```
=> chore(make): Add target to run MkDocs server and preview docs

README.md
The README contained an outdated starboard command in its polaris example.
Fixes #293
Signed-off-by: Christian Zunker <christian.zunker@codecentric.cloud>
=> Fix polaris example in README

pkg/report/templates/default.qtpl, pkg/report/templates/default.qtpl.go, pkg/vulnerabilityreport/writer.go
=> refactor: Delete WorkloadVulnerabilities type

docs/cli/installation/docker.md, docs/operator/installation/helm.md, docs/operator/installation/kubectl.md, docs/operator/installation/olm.md, docs/settings.md, mkdocs.yml
in the [lates version](https://operatorhub.io/operator/starboard-operator) we changed the way vulnerability scanners are configured.  Instead of using env the operator reads config objects in the namespace where it's installed.
You can preview docs by running `make mkdocs-serve`
=> docs(olm): Update docs how to install operator from OperatorHub.io

pkg/cmd/scan_configaudit.go, pkg/configauditreport/plugin.go, pkg/polaris/scanner.go, pkg/polaris/scanner_test.go, pkg/vulnerabilityreport/scanner.go
This is a preliminary step to onboard Popeye or any other configuration auditing tool and reuse code to integrate Polaris with Starboard Operator.
=> refactor: Define interface for resource configuration checkers

pkg/kube/pod/manager.go, pkg/kube/runnable_job.go, pkg/vulnerabilityreport/scanner.go
It might happen that a scan job cannot be created. In such cases Starboard CLI hangs forever because it watches the job's status to terminate (JobComplete or JobFailed). However, some failures are reported as Kubernetes events associated with the scan job.
This change adds the events informer to watch events associated with a scan job, and terminate the program when the event of type EventTypeWarning (= error for Kubernetes) is detected.
To reproduce you can delete the starboard service account in the starborad namespace:
```
kubectl delete sa -n starboard starboard
```
```console
$ kubectl starboard generate vulnerabilityreports deploy/nginx -v 3
I0111 14:33:00.321886   35566 cert_rotation.go:137] Starting client certificate rotation controller
I0111 14:33:00.351359   35566 …
```
=> feat(cli): Provide more details when scan job fails

cmd/starboard-operator/main.go, go.mod, go.sum, pkg/operator/controller/analyzer.go, pkg/operator/controller/job/job_controller.go, pkg/operator/controller/pod/pod_controller.go, pkg/operator/controller/reconciler.go, pkg/operator/etc/config.go, pkg/operator/etc/config_test.go, pkg/operator/operator.go
=> refactor: Simplify struct used to configure the operator

pkg/apis/aquasecurity/v1alpha1/config_audit_types.go, pkg/polaris/plugin.go, pkg/polaris/plugin_test.go
Fixes #334.
Here is the output I get for the `nginx` deployment from the [getting started](https://aquasecurity.github.io/starboard/cli/getting-started/) docs:
```shell
$ kubectl create deployment nginx --image nginx:1.16
$ starboard scan vulnerabilityreports deployment/nginx
$ kubectl get configauditreports.aquasecurity.github.io -o wide
NAME               SCANNER   AGE   PASS   DANGER   WARNING
deployment-nginx   Polaris   1s    9      0        8
```
=> Add passing checks count to configauditreport summary

pkg/polaris/plugin.go, pkg/polaris/plugin_test.go
This PR adds SecurityContexts to the `polaris` Job in order to run the job with the least amount of privilege possible, in partial fulfillment of #163.
I ran the job with and without the changes in a local kind cluster and I did not see a difference in the output.
To obtain the output, I ran:
```
kubectl create deployment nginx --image nginx:1.16
kubectl wait --for=condition=available deploy/nginx --timeout=60s
./bin/starboard scan configauditreports deployment/nginx
./bin/starboard get configaudit deployment/nginx -o yaml >cars.yaml
```
=> Set security context for polaris

pkg/trivy/plugin.go, pkg/trivy/plugin_test.go
This PR adds SecurityContexts to the `trivy` Job in order to run the job with the least amount of privilege possible, in partial fulfillment of #163.
I ran the job with and without the changes in a local kind cluster and I did not see a difference in the output.
To obtain the output, I ran:
```
kubectl create deployment nginx --image nginx:1.16
kubectl wait --for=condition=available deploy/nginx --timeout=60s
./bin/starboard scan vulnerabilityreports deployment/nginx
./bin/starboard get vulnerabilities deployment/nginx -o yaml >vulns.yaml
```
---
Looking at issues on the `trivy` repo, I found this issue: https://github.com/aquasecurity/trivy/issues/580, where running as a non-root user was causing `trivy` to be unable to run. It seems that this was due to using the Docker socket, which is …
=> Set security context for trivy

pkg/operator/controller/configauditreport.go, pkg/operator/controller/vulnerabilityreport.go, pkg/operator/etc/config.go, pkg/operator/etc/config_test.go, pkg/operator/operator.go, pkg/operator/predicate/predicate.go, pkg/operator/predicate/predicate_test.go
=> fix(operator): Skip workloads in the operator namespace

Makefile, pkg/resources/doc.go, pkg/resources/resources.go, pkg/resources/resources_test.go
Note that kublet can manage pods independently by reading pod definition
files from a configured host directory (typically /etc/kubernetes/manifests).
Such pods are called *static pods* and are owned by a cluster Node.
So far we could not save vulnerability and config audit reports for such pods.
In this commit we treat them as unmanaged pods. (Otherwise we'd require
cluster-scoped permissions to get Nodes in order to set the owner reference
when we create an instance of custom resource.)
Resolves: #234
=> fix: Save security reports for static pods

pkg/resources/resources.go, pkg/resources/resources_test.go
Pods created and controlled by third party frameworks,
such as Argo workflow engine, are considered as unmanaged.
Otherwise we'd need to maintain and extend the list of
RBAC permissions over time.
Resolves: #373
=> feat: Manage pods controlled by third parties

pkg/starboard/config.go, pkg/starboard/config_test.go
This PR addresses a potential issue with the `kube-hunter.quick` configuration param. It doesn't make much sense for this parameter to be required, since it's a fairly specific setting that a significant portion of users may not care about.
(This PR was inspired by https://github.com/aquasecurity/starboard/discussions/386.)
=> Make kubehunter quick config param optional

deploy/helm/templates/deployment.yaml, docs/operator/configuration.md
=> fix(helm): Configure service account assigned to operator's pod

pkg/kubebench/scanner.go
This PR adds `SecurityContext`s to the `kube-bench` `Job` in order to run the job with the least amount of privilege possible, in partial fulfillment of #163.
I ran the job with and without the changes in a local `kind` cluster and I did not see a difference in the output.
=> Set security context for kube-bench

pkg/report/templates/default.qtpl, pkg/report/templates/default.qtpl.go
=> feat: Add AVD links to HTML report

pkg/cmd/get_configaudit.go, pkg/cmd/get_report.go, pkg/cmd/scan_configaudit.go, pkg/configauditreport/io.go, pkg/configauditreport/io_test.go, pkg/operator/operator.go, pkg/report/html.go
=> feat: Get configauditreports from ReplicaSet in the same hierarchy

go.sum, pkg/cmd/get_report.go, pkg/cmd/get_vulnerabilities.go, pkg/cmd/scan_vulnerabilities.go, pkg/configauditreport/io.go, pkg/kubebench/converter_test.go, pkg/operator/operator.go, pkg/report/html.go, pkg/vulnerabilityreport/io.go, pkg/vulnerabilityreport/io_test.go
=> refactor: vulnerabilityreport.ReadWriter to use controller-runtime Client

.github/workflows/release.yaml
If I understand correctly, `docker/login-action@v1` log out from the Docker registry by default. Am I missing something?
https://github.com/docker/login-action#inputs
https://github.com/aquasecurity/starboard/runs/1901817059?check_suite_focus=true
=> chore(release): remove logout step

CONTRIBUTING.md, Makefile, deploy/helm/templates/rbac.yaml, deploy/helm/values.yaml, deploy/static/03-starboard-operator.clusterrole.yaml, deploy/static/06-starboard-operator.deployment.yaml, docs/operator/configuration.md, go.mod, go.sum, itest/starboard-operator/starboard_operator_test.go, itest/starboard-operator/suite_test.go, itest/starboard/starboard_cli_test.go, pkg/kube/starboard.go, pkg/kubebench/scanner.go, pkg/operator/controller/ciskubebenchreport.go, pkg/operator/controller/configauditreport.go, pkg/operator/controller/vulnerabilityreport.go, pkg/operator/etc/config.go, pkg/operator/operator.go, pkg/operator/predicate/predicate.go
=> feat(operator): Integrate kube-bench

deploy/static/05-starboard-operator.config.yaml, deploy/trivy-server/03-trivy-server.deployment.yaml, deploy/trivy-server/README.md, docs/settings.md, itest/starboard/starboard_cli_test.go, pkg/starboard/config.go
=> chore: Bump up Trivy from v0.14.0 to v0.16.0

pkg/configauditreport/plugin.go, pkg/configauditreport/scanner.go, pkg/docker/doc.go, pkg/kube/pod/manager.go, pkg/operator/controller/configauditreport.go, pkg/plugin/polaris/plugin.go, pkg/plugin/polaris/plugin_test.go
=> feat: Pass K8s object to configauditreport.Plugin

pkg/apis/aquasecurity/v1alpha1/kube_hunter_types.go, pkg/operator/controller/ciskubebenchreport.go, pkg/plugin/polaris/plugin_test.go
=> chore: Review log statements and error messages

deploy/helm/templates/configmap.yaml, deploy/helm/values.yaml
=> Add ConfigMap template for plugins configuration

CONTRIBUTING.md
Without the OPERATOR_NAMESPACE env var, operator integration tests fail with messages like: 
```
Unexpected error:
<*fmt.wrapError | 0xc0005b4400>: {
msg: "resolving install mode: OPERATOR_NAMESPACE must be set",
err: {
s: "OPERATOR_NAMESPACE must be set",
},
}
resolving install mode: OPERATOR_NAMESPACE must be set
occurred
```
Without first running the prerequisite steps to add the starboard-operator namespace to the cluster, operator integration tests fails with messages like:
```
Unexpected error:
<*errors.StatusError | 0xc000738f00>: {
ErrStatus: {
TypeMeta: {Kind: "", APIVersion: ""},
ListMeta: {
SelfLink: "",
ResourceVersion: "",
Continue: "",
RemainingItemCount: nil,
},
Status: "Failure",
Message: "namespaces \"starboard-operator\" not found",
Reason: "NotFound",
Details: {
Name: …
```
=> doc: Clarify prereqs and env vars to run operator integration tests

docs/cli/getting-started.md
Just a minor doc fix: The correct command is `starboard get configaudit`, but the doc said `starboard get configauditreport`. This PR updates the doc to match the command.
=> doc: Update cli docs to show the correct command to get configaudit

deploy/helm/templates/deployment.yaml, deploy/helm/templates/rbac.yaml, deploy/helm/values.yaml, deploy/static/03-starboard-operator.clusterrole.yaml, docs/operator/configuration.md, pkg/operator/etc/config.go, pkg/operator/operator.go, pkg/starboard/config.go
Resolves https://github.com/aquasecurity/starboard/issues/219
=> Add HA Support for the Starboard Operator

itest/matcher/doc.go, itest/matcher/matcher.go, itest/matcher/matcher_test.go, itest/starboard/starboard_cli_test.go
=> refactor: Use custom Gomega matcher to assert VulnerabilityReports

itest/matcher/matcher.go, itest/matcher/matcher_test.go, itest/starboard-operator/starboard_operator_test.go, pkg/kube/resources.go, pkg/kube/resources_test.go, pkg/operator/controller/ciskubebenchreport.go, pkg/operator/controller/configauditreport.go, pkg/operator/controller/vulnerabilityreport.go, pkg/operator/predicate/predicate.go, pkg/operator/predicate/predicate_test.go, pkg/vulnerabilityreport/builder.go, pkg/vulnerabilityreport/builder_test.go
=> feat: Deleting a VulnerabilityReport should trigger rescan

pkg/report/html.go, pkg/report/sort.go, pkg/report/sort_test.go, pkg/report/templates/namespace_report.qtpl, pkg/report/templates/namespace_report.qtpl.go, pkg/report/templates/types.go
Sample output:
Resolves https://github.com/aquasecurity/starboard/issues/410
=> feat(cli): Show top 5 failed workload configuration checks in html report for namespace

CONTRIBUTING.md, deploy/helm/values.yaml, deploy/static/06-starboard-operator.deployment.yaml, docs/operator/configuration.md, pkg/operator/etc/config.go, pkg/operator/operator.go
=> feat(operator): Add config to enable/disable scanners

pkg/cmd/scan_configaudit.go, pkg/configauditreport/plugin.go, pkg/configauditreport/scanner.go, pkg/operator/controller/configauditreport.go, pkg/operator/operator.go, pkg/plugin/polaris/plugin.go, pkg/plugin/polaris/plugin_test.go, pkg/starboard/doc.go, pkg/starboard/plugin.go, pkg/starboard/plugin_test.go
=> feat: Add PluginContext for configuration audit scanners

deploy/helm/Chart.yaml, deploy/static/06-starboard-operator.deployment.yaml, mkdocs.yml
=> release: Prepare v0.10.0-rc3

pkg/operator/controller/plugins_config.go, pkg/operator/predicate/predicate.go, pkg/operator/predicate/predicate_test.go, pkg/plugin/conftest/plugin.go, pkg/starboard/plugin.go, pkg/starboard/plugin_test.go
This wasn't an issue and we were handling ConfigMap deletion as
expected. However, I took this oportunity to refactor the code
a bit and use predicate instead of conditionally ingoring ConfigMap
events in the reconciliation loop. With predicate the events that
we're not interested in are not even added to the worker queue.
Resolves: #482
=> refactor(conftest): Skip rescan when plugin ConfigMap is deleted

pkg/plugin/polaris/plugin.go, pkg/plugin/polaris/plugin_test.go
=> fix(polaris): Remove clutter from JSON output

deploy/helm/Chart.yaml, deploy/static/06-starboard-operator.deployment.yaml, mkdocs.yml
=> release: Prepare v0.10.0-rc5

go.mod, go.sum, pkg/plugin/conftest/plugin.go, pkg/plugin/conftest/plugin_test.go
When we created a scan Job for config audits it referred directly
to the starboard-conftest-config ConfigMap. However, the ConfigMap
might have changed before the Job was run. When we removed a policy
from the ConfigMap the Job got stuck in the Pending state due to
non-existent config key error.
The solution is to copy policies to a temporary Secret and associate
it with the scan Job so we're agnostic to changes of the
starboard-conftest-config ConfigMap.
Resolves: #509
=> fix(Conftest): Error: configmap references non-existent config key

itest/starboard/starboard_cli_test.go, itest/starboard/suite_test.go, pkg/operator/operator.go, pkg/plugin/conftest/plugin.go, pkg/plugin/conftest/plugin_test.go
For upstream K8s cluster scan Jobs will run as USER defined in
the Conftest container image. For OpenShift Container Platform
the admission controller will assign UID and GID based on the
range defined for the OpenShift project / K8s namespace where
Starboard is installed.
=> fix(Conftest): Do not specify UID (1000) and GID (1000) in SecurityContext

deploy/static/05-starboard-operator.config.yaml, pkg/starboard/config.go, pkg/starboard/config_test.go
=> feat: Ensure default config should not create ConfigMap for Polaris when it is not chosen as plugin

itest/matcher/matcher.go, pkg/configauditreport/builder.go, pkg/configauditreport/builder_test.go, pkg/configauditreport/scanner.go, pkg/operator/controller/ciskubebenchreport.go, pkg/operator/controller/configauditreport.go, pkg/operator/controller/limit_checker.go, pkg/operator/controller/limit_checker_test.go, pkg/operator/controller/vulnerabilityreport.go, pkg/operator/predicate/predicate.go, pkg/operator/predicate/predicate_test.go, pkg/plugin/conftest/plugin_test.go, pkg/plugin/factory.go, pkg/plugin/polaris/plugin_test.go, pkg/starboard/constants.go, pkg/starboard/plugin.go, pkg/starboard/plugin_test.go
=> refactor: Use builder for config audit scan jobs

pkg/configauditreport/builder.go, pkg/operator/controller/configauditreport.go, pkg/plugin/conftest/plugin.go, pkg/plugin/conftest/plugin_test.go
=> feat: Use deterministic names for Secrets created by Conftest plugin

CONTRIBUTING.md, docs/operator/installation/olm.md
=> chore: Upgrade OLM from v0.16.1 to 0.17.0

.github/workflows/build.yaml, .github/workflows/release.yaml, itest/helper/helper.go, itest/starboard-operator/starboard_operator_test.go, itest/starboard-operator/suite_test.go
=> refactor: Split specs in integration test for operator

deploy/helm/values.yaml, deploy/static/05-starboard-operator.config.yaml, docs/settings.md, itest/matcher/matcher.go, itest/starboard-operator/configauditreport/conftest/suite_test.go, pkg/plugin/conftest/plugin.go, pkg/plugin/conftest/plugin_test.go, pkg/starboard/config.go
=> feat(Conftest): Upgrade Conftest from v0.23.0 to v0.25.0 and use --no-fail flag

docs/settings.md, pkg/plugin/trivy/plugin.go, pkg/plugin/trivy/plugin_test.go, pkg/starboard/config.go, pkg/starboard/config_test.go
Resolves: https://github.com/aquasecurity/starboard/issues/545
=> feat(trivy): Configure insecure image registries

pkg/kube/secrets.go, pkg/kube/secrets_test.go, pkg/plugin/trivy/plugin.go, pkg/plugin/trivy/plugin_test.go
=> fix: Handle legacy image pull secrets of type kubernetes.io/dockercfg

pkg/plugin/polaris/plugin.go, pkg/plugin/polaris/plugin_test.go
=> fix: Running Polaris on OpenShift fails

docs/settings.md, pkg/plugin/trivy/plugin.go, pkg/plugin/trivy/plugin_test.go, pkg/starboard/config.go, pkg/starboard/config_test.go
Resolves: https://github.com/aquasecurity/starboard/issues/541
=> feat(trivy): Pass additional settings to Trivy client

pkg/operator/controller/vulnerabilityreport.go, pkg/vulnerabilityreport/builder.go, pkg/vulnerabilityreport/builder_test.go, pkg/vulnerabilityreport/scanner.go
=> refactor(cli): Use deterministic names for vulnerability scan jobs

itest/matcher/matcher.go, pkg/operator/controller/vulnerabilityreport.go, pkg/vulnerabilityreport/scanner.go
=> feat(cli): Add pod template hash to vulnerability report

deploy/helm/templates/config.yaml, deploy/static/05-starboard-operator.config.yaml, docs/integrations/config-checkers/conftest.md, itest/starboard-operator/configauditreport/conftest/suite_test.go, itest/starboard/suite_test.go, pkg/configauditreport/builder_test.go, pkg/configauditreport/plugin.go, pkg/configauditreport/scanner.go, pkg/operator/controller/configauditreport.go, pkg/plugin/conftest/plugin.go, pkg/plugin/conftest/plugin_test.go, pkg/plugin/factory.go, pkg/plugin/polaris/plugin.go, pkg/plugin/polaris/plugin_test.go, pkg/starboard/config.go, pkg/starboard/config_test.go, pkg/starboard/plugin.go
=> refactor: Remove config checkers config from generic starboard ConfigMap

pkg/operator/controller/vulnerabilityreport.go, pkg/plugin/aqua/plugin.go, pkg/plugin/trivy/plugin.go, pkg/plugin/trivy/plugin_test.go, pkg/vulnerabilityreport/plugin.go, pkg/vulnerabilityreport/scanner.go
=> refactor: Add PluginContext to ParseVulnerabilityReportData callback

itest/starboard/starboard_cli_test.go, pkg/cmd/scan_configauditreports.go, pkg/configauditreport/builder_test.go, pkg/configauditreport/plugin.go, pkg/operator/operator.go, pkg/plugin/conftest/plugin.go, pkg/plugin/conftest/plugin_test.go, pkg/plugin/polaris/plugin.go, pkg/plugin/polaris/plugin_test.go, pkg/starboard/config.go, pkg/starboard/config_test.go, pkg/starboard/plugin.go
=> refactor: Allow plugins to provide the default config

deploy/helm/templates/config.yaml, deploy/static/05-starboard-operator.config.yaml, pkg/cmd/cleanup.go, pkg/cmd/init.go, pkg/cmd/installer.go, pkg/cmd/root.go, pkg/cmd/scan_configauditreports.go, pkg/operator/operator.go, pkg/plugin/aqua/plugin.go, pkg/plugin/factory.go, pkg/plugin/trivy/plugin.go, pkg/plugin/trivy/plugin_test.go, pkg/starboard/config.go, pkg/starboard/plugin.go, pkg/vulnerabilityreport/plugin.go
We started off with all config settings read from the starboard
ConfigMap and the starboard Secret. However, this does not scale
well with a number of plugins and configuration options.
This commit allows Triy plugin to read its settings from
the starboard-trivy-config ConfigMap and the starboard-trivy-config
Secret.
=> refactor(trivy): Read config from starboard-trivy-config ConfigMap

docs/operator/installation/helm.md
A Helm installation with default values left crd `kubehunterreports.aquasecurity.github.io` on our system after going through the uninstall steps. We confirmed no other aquasecurity crd's were left.
This PR adds the missing crd to the uninstall documentation. It appears my editor also removed a trailing newline at the end of the file.
=> docs: Manual removal of installed crds

deploy/helm/templates/config.yaml, deploy/helm/values.yaml, deploy/static/05-starboard-operator.config.yaml, pkg/plugin/trivy/plugin.go, pkg/plugin/trivy/plugin_test.go
This PR solves the problem reported in #572: with for new configuration values the resource/limit requirements of the trivy pod can be adjusted.
Defaults are added to the Helm charts and k8s resources:
```
#k8s resource requests and limits
resources:
request:
cpu: 100m
memory: 100M
limit:
cpu: 500m
memory: 500M
```
But configmap of existing custom instances should be updated to use limits as before.
=> Introduce resource request/limit parameters for trivy pod 

pkg/cmd/get_configaudit.go, pkg/cmd/scan_configauditreports.go, pkg/configauditreport/io.go, pkg/configauditreport/io_test.go, pkg/operator/controller/configauditreport.go, pkg/report/html.go
=> feat: Define interface for saving and finding ClusterConfigAuditReports

deploy/helm/templates/config.yaml, deploy/helm/values.yaml, deploy/static/05-starboard-operator.config.yaml, docs/integrations/vulnerability-scanners/trivy.md, docs/settings.md, pkg/plugin/trivy/plugin.go, pkg/plugin/trivy/plugin_test.go
=> chore(trivy): Rename properties to configure resource requirements and limits

deploy/helm/templates/config.yaml, deploy/helm/values.yaml, docs/integrations/vulnerability-scanners/trivy.md, docs/operator/installation/helm.md
=> feat(helm): Configure Trivy settings

.github/workflows/build.yaml, .github/workflows/release.yaml, CONTRIBUTING.md, docs/operator/installation/kubectl.md, docs/operator/installation/olm.md, embedded.go, itest/starboard/starboard_cli_test.go, pkg/apis/aquasecurity/v1alpha1/config_audit_types.go, pkg/cmd/installer.go
=> feat: Install ClusterConfigAuditReport CRD

pkg/kubehunter/scanner.go
This PR includes a temporary fix for **log** related problem.
Issue ID: https://github.com/aquasecurity/starboard/issues/631
Solution Reference: https://github.com/aquasecurity/kube-hunter/issues/465
=> FIX: Updated log level as temporary solution

pkg/plugin/conftest/plugin.go
=> fix(conftest): Add Deployment to supported kinds

pkg/kube/logs.go
related to #627, but there are probably more to it. this is as far as I can replicate the problem at the moment, though the [original issue using previous version of starboard](https://github.com/aquasecurity/starboard/issues/627#issue-928389840) might have different cause as log also shows `apimachinery` panic handler.
```
2021-09-05T13:09:11.687Z    INFO    controller-runtime.manager.controller.cronjob    Starting workers    {"reconciler group": "batch", "reconciler kind": "CronJob", "worker count": 1}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1303d09]
goroutine 547 [running[]:
github.com/aquasecurity/starboard/pkg/kube.(*logsReader).GetLogsByJobAndContainerName(0xc0004a5b20, {0x19b9698, …
```
=> fix: Handle nil pod in get pod by job

docs/integrations/vulnerability-scanners/trivy.md, pkg/plugin/trivy/plugin.go, pkg/plugin/trivy/plugin_test.go
This patch adds the option to use mirrors for the docker registries in trivy.
This way it is possible to download the images from self-hosted mirrors instead
of e.g. index.docker.io. This has some benefits, like not being hit by download
restrictions.
I tried to also add this new Feature to the docs and I also wrote unit tests for it.
In the contributing guidelines is mentioned that for every PR there should also be a issue, but when generating a new issue of kind feature request, I am redirected to the discussion. So I skipped creating an issue for this, but I can do it afterwards, if necessary. For now I will point to the already existing discussion #260.
=> Add Registry Mirrors to Trivy

CONTRIBUTING.md, build/mkdocs-material/Dockerfile, docs/operator/installation/olm.md
=> chore(deps): Bump up OLM from v0.17.0 to v0.18.3

docs/cli/getting-started.md, pkg/cmd/get.go, pkg/cmd/root.go
=> chore: Replace starboard get report with starboard report command

docs/cli/getting-started.md, embedded.go, itest/starboard/starboard_cli_test.go, pkg/apis/aquasecurity/v1alpha1/vulnerability_types.go, pkg/cmd/cleanup.go, pkg/cmd/init.go, pkg/cmd/installer.go, pkg/cmd/report.go, pkg/cmd/root.go
=> feat(cli): Install clustervulnerabilityreports CRD

.github/workflows/build.yaml, .github/workflows/release.yaml
Fixes #652
Signed-off-by: Christian Zunker <christian.zunker@codecentric.cloud>
=> chore(ci): Add KinD connection test to `integration-operator-conftest`

Makefile, itest/starboard/starboard_cli_test.go, itest/starboard/suite_test.go, pkg/configauditreport/scanner.go, pkg/kube/object.go, pkg/kube/object_test.go, pkg/vulnerabilityreport/scanner.go
feat(cli): Resolve report owners to be consistent with operator
Starboard CLI was not consistent with Starboard Operator
when it comes to assigning VulnerabilityReports and ConfigAuditReports
to K8s workloads. For example, the report generated by the following
command was controlled by the nginx Deployment, whereas the Operator
would associate it with the active ReplicaSet (aka current revision).
starboard scan vulnerabilityreports deploy/nginx
With this patch Starboard CLI will resolve the current revision of
a Deployment and use it as the owner of VulnerabilityReport and
ConfigAuditReport instances.
=> feat(cli): Resolve report owners to be consistent with operator

deploy/static/02-starboard-operator.rbac.yaml, deploy/static/03-starboard-operator.config.yaml, deploy/static/04-starboard-operator.deployment.yaml
=> chore(deploy): add recommended labels

CONTRIBUTING.md, deploy/helm/templates/_helpers.tpl, deploy/helm/templates/config.yaml, deploy/helm/templates/deployment.yaml, deploy/helm/values.yaml, deploy/static/03-starboard-operator.config.yaml, deploy/static/04-starboard-operator.deployment.yaml, docs/integrations/config-checkers/conftest.md, docs/operator/configuration.md, pkg/operator/etc/config.go
=> chore(deploy): align static YAMLs with Helm templates

pkg/kube/object.go, pkg/plugin/conftest/plugin_test.go
=> fix: list active ReplicaSets in the given namespace

pkg/operator/controller/vulnerabilityreport.go
This patch is solving a regression where we did not set
a namespace for secrets that are referred to by vulnerability
scan jobs.
Resolves: #835
=> fix: scan images from private registries

build/scanner-aqua/Dockerfile, build/starboard-operator/Dockerfile, build/starboard/Dockerfile
Upgrade starboard base container CVE-2021-3711,CVE-2021-36159.
=> (fix) Upgrade starboard base container CVE-2021-3711,CVE-2021-36159.

pkg/docker/config.go, pkg/docker/config_test.go
=> fix: parse registry credentials when auth is blank

.github/workflows/mkdocs-deploy.yaml, .github/workflows/publish-helm-chart.yaml
=> chore(ci): publish mkdocs and Helm chart from the specified ref

pkg/kube/logs.go
=> fix: typo in GetLogsByJobAndContainerName error message

.github/workflows/publish-docs.yaml, RELEASING.md
=> chore: describe release steps

.github/workflows/build.yaml
- Run the testing helm chart in the PR (only 'deploy/helm/**')
- Separate the release chart in another job.
=> chore: test the helm chart in the PR

CONTRIBUTING.md, deploy/helm/templates/deployment.yaml, deploy/helm/templates/rbac.yaml, deploy/helm/values.yaml, deploy/static/02-starboard-operator.rbac.yaml, deploy/static/04-starboard-operator.deployment.yaml, docs/operator/configuration.md, docs/operator/getting-started.md, pkg/kube/object.go, pkg/kube/object_test.go, pkg/operator/controller/vulnerabilityreport.go, pkg/operator/etc/config.go
Add environment variable: OPERATOR_VULNERABILITY_SCANNER_LATEST to be configured in the operator.
Setting this value to true will look through new replicasets and see if `deployment.kubernetes.io/revision` matches with it's deployment owner.
If that is true generate a report, else ignore it.
Solves:
https://github.com/aquasecurity/starboard/discussions/858
https://github.com/aquasecurity/starboard/discussions/668
=> feat(vulnrebilityreports) Only show the latest vulnrebilityreports from a deployment

itest/helper/helper.go, itest/matcher/matcher.go, itest/starboard/starboard_cli_test.go, pkg/cmd/commands.go, pkg/configauditreport/builder.go, pkg/configauditreport/builder_test.go, pkg/configauditreport/io.go, pkg/configauditreport/io_test.go, pkg/configauditreport/scanner.go, pkg/kube/object.go, pkg/kube/object_test.go, pkg/kubebench/io.go, pkg/kubebench/io_test.go, pkg/operator/controller/ciskubebenchreport.go, pkg/operator/controller/configauditreport.go, pkg/operator/controller/vulnerabilityreport.go, pkg/plugin/conftest/plugin_test.go, pkg/report/html.go, pkg/report/report.go, pkg/report/templates/types.go, pkg/vulnerabilityreport/builder.go, pkg/vulnerabilityreport/builder_test.go, pkg/vulnerabilityreport/io.go, pkg/vulnerabilityreport/io_test.go, pkg/vulnerabilityreport/scanner.go
There is no good moment for such refactoring but I found
kube.Object pretty confusing with ubiquitous client.Object
defined by the controller-runtime module. We use both
types throughout the code in the same source files
so this patch renames kube.Object to kube.ObjectRef.
=> refactor: rename kube.Object to kube.ObjectRef

pkg/plugin/aqua/plugin.go, pkg/plugin/trivy/plugin.go, pkg/plugin/trivy/plugin_test.go, pkg/vulnerabilityreport/builder.go, pkg/vulnerabilityreport/builder_test.go, pkg/vulnerabilityreport/plugin.go
This is needed for future development where we need more information on the object which we are scanning.
=> refactor: vulnerability plugin contract to accept client.Object 

pkg/plugin/trivy/plugin.go, pkg/plugin/trivy/plugin_test.go
Fixes #888
Had to reorder the args a little because `--skip-update` belongs to the
image subcommand now
=> PET-1192 - Add image subcommand to trivy plugin

deploy/helm/templates/config.yaml, deploy/helm/values.yaml, docs/settings.md, pkg/configauditreport/builder.go, pkg/configauditreport/scanner.go, pkg/kubebench/scanner.go, pkg/kubehunter/scanner.go, pkg/operator/controller/ciskubebenchreport.go, pkg/operator/controller/configauditreport.go, pkg/operator/controller/vulnerabilityreport.go, pkg/starboard/config.go, pkg/starboard/config_test.go, pkg/starboard/constants.go, pkg/vulnerabilityreport/builder.go, pkg/vulnerabilityreport/scanner.go
This is the preparation for the use of starboard together with https://github.com/Azure/aad-pod-identity. This is necessary to support Azure Acr #278.
also this https://github.com/aquasecurity/fanal/pull/371 is needed  to allow trivy to pull from acr.
=> feat: add pod template labels to scanJob

pkg/kube/object.go, pkg/operator/controller/vulnerabilityreport.go, pkg/plugin/factory.go, pkg/plugin/trivy/plugin.go, pkg/plugin/trivy/plugin_test.go, pkg/vulnerabilityreport/builder_test.go
``trivy.command: fs`` will change the trivy scan option to pick up vulnerability scans
using trivy fs scan command
This is the implementation of first approach suggested here #830
=> feat: Vulnerability scan using Trivy fs scan command

.github/workflows/build.yaml, .github/workflows/release.yaml, CONTRIBUTING.md, go.mod
This upgrade is required to keep up with recent client-go
and controller-runtime dependencies.
=> chore(deps): bump Go from 1.16 to 1.17

cmd/starboard-operator/main.go
=> fix: handle error when operator cannot start

docs/design/design_vuln_scan_job_in_same_namespace_of_workload.md, docs/settings.md, pkg/operator/controller/limit_checker.go, pkg/operator/controller/limit_checker_test.go, pkg/operator/controller/vulnerabilityreport.go, pkg/operator/operator.go, pkg/plugin/factory.go, pkg/plugin/trivy/plugin.go, pkg/plugin/trivy/plugin_test.go, pkg/starboard/config.go, pkg/starboard/plugin.go, pkg/vulnerabilityreport/builder.go, pkg/vulnerabilityreport/builder_test.go
new option in configmap starboard has added ie. ``vulnerabilityReports.scanJobsInSameNamespace`` to enable running
scan job in the workload namespace.
Once this option is enabled then vulnerability scan jobs will start running in same namespace of workload.
Also it will run with same serviceAccount and imagepullSecret of workload.
This option helps us to schedule scan job with Trivy fs command on any node.
this implements the approach mentioned here: https://github.com/aquasecurity/starboard/pull/917
=> feat: Add option to run Vuln scan job in worload namespace

cmd/scanner-aqua/main.go, pkg/plugin/aqua/client/client.go, pkg/plugin/aqua/client/client_integration_test.go, pkg/plugin/aqua/client/client_test.go, pkg/plugin/aqua/scanner/api/scanner.go, pkg/plugin/aqua/scanner/cli/scanner.go, pkg/plugin/aqua/scanner/cli/types.go
1. starboard-scanner-aqua shim to support filesystem command, so that scannercli fs-scan commnad is executed.
2. refactor code to get auth-key from aqua console api url
=> feat(starboard-scanner-aqua): Add support for fs scan option

.github/workflows/release-snapshot.yaml, .github/workflows/release.yaml
=> fix(ci): use Go 1.17 in release snapshot workflow

deploy/helm/values.yaml, deploy/static/03-starboard-operator.config.yaml, deploy/static/starboard.yaml, docs/integrations/vulnerability-scanners/trivy.md, itest/matcher/matcher.go, itest/matcher/matcher_test.go, pkg/plugin/trivy/plugin.go, pkg/plugin/trivy/plugin_test.go
Signed-off-by: Engin Diri <engin.diri@mail.schwarz>
This PR fixes #1007, this is needed to ensure the #1003 is working, as we need the TRIVY_INSECURE flag.
=> chore: version bump of trivy to 0.24.2

pkg/configauditreport/controller.go, pkg/policy/policy.go, pkg/policy/policy_test.go
This will allow us to use the aquasecurity/defsec module
to load and evaluate Rego policies.
=> refactor: decouple policy pkg from starboard apis

deploy/helm/templates/rbac.yaml
Initially, we wanted to implement the least privileged principle
by creating Role or ClusterRole depending on install mode.
For example, we created Role if the target namespace was the same
as the operator namespace. However, this logic was too simple
because we have cluster-scoped CRDs, e.g. CISKubeBenchReport, that
require ClusterRole to grant RBAC permissions.
Resolves: #1001
=> fix(helm): grant permissions to get,list,watch ciskubebenchreports

deploy/crd/clustercompliancedetailreports.crd.yaml, deploy/crd/clustercompliancereports.crd.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/starboard.yaml, docs/design/design_compliance_report.md, pkg/apis/aquasecurity/v1alpha1/compliance_types.go, pkg/apis/aquasecurity/v1alpha1/compliancedetail_types.go, pkg/compliance/io.go, pkg/compliance/testdata/fixture/clusterComplianceDetailReport.json, pkg/compliance/testdata/fixture/clusterComplianceReport.json, pkg/compliance/testdata/fixture/clusterComplianceSpec.json, pkg/compliance/testdata/fixture/nsa-1.0.yaml, pkg/compliance/testdata/fixture/nsa-1.0_no_controls.yaml
remove  specKind field from compliance reports
=> fix: remove compliance specKind field

pkg/compliance/clustercompliancereport_test.go, pkg/compliance/testdata/fixture/cisBenchmarkReportUpdate.json, pkg/compliance/testdata/fixture/clusterComplianceReportUpdate.json, pkg/compliance/testdata/fixture/configAuditReportUpdate.json
Add compliance reconcile test to validate that compliance status is updated (after initial generation) following to change with cis-bench and audit config reports
=> test: update compliance reconcile tests

embedded.go, itest/matcher/matcher.go, itest/matcher/matcher_test.go, itest/starboard/starboard_cli_test.go, itest/starboard/suite_test.go, pkg/cmd/scan_configauditreports.go, pkg/configauditreport/controller.go, pkg/configauditreport/scanner.go, pkg/starboard/config.go, pkg/starboard/constants.go
=> feat(cli): use built-in scanner for configuration audits

.goreleaser.yaml
The official Starboard images are labeled following [the org.label-schema Label Schema](https://label-schema.org/). That schema has been deprecated in favor of [the superseeding OCI image spec annotations](https://github.com/opencontainers/image-spec/blob/main/annotations.md#back-compatibility-with-label-schema).
=> feat: using oci image spec annotations

embedded.go, itest/starboard/starboard_cli_test.go, pkg/apis/aquasecurity/v1alpha1/compliance_types.go, pkg/apis/aquasecurity/v1alpha1/compliancedetail_types.go, pkg/cmd/commands.go, pkg/cmd/get.go, pkg/cmd/get_clustercompliancereport.go, pkg/cmd/installer.go, pkg/compliance/clustercompliancereport.go, pkg/compliance/io.go
=> feat: compliance support for cli

.goreleaser.yaml, deploy/crd/ciskubebenchreports.crd.yaml, deploy/crd/clustercompliancedetailreports.crd.yaml, deploy/crd/clustercompliancereports.crd.yaml, deploy/crd/clusterconfigauditreports.crd.yaml, deploy/crd/clustervulnerabilityreports.crd.yaml, deploy/crd/configauditreports.crd.yaml, deploy/crd/kubehunterreports.crd.yaml, deploy/crd/vulnerabilityreports.crd.yaml, deploy/helm/Chart.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/01-starboard-operator.ns.yaml, deploy/static/02-starboard-operator.rbac.yaml, deploy/static/03-starboard-operator.config.yaml, deploy/static/04-starboard-operator.policies.yaml, deploy/static/05-starboard-operator.deployment.yaml, deploy/static/starboard.yaml
=> release: prepare v0.15.0-rc5

docs/tutorials/recommended_labels.rego, docs/tutorials/writing_custom_configaudit_policies.md, mkdocs.yml
To preview docs on this branch run `make mkdocs-serve` and then open [http://localhost:8000](http://localhost:8000) in your browser.
=> docs(tutorial): Writing Custom Configuration Audit Policies

pkg/compliance/clustercompliancereport.go, pkg/compliance/io.go
Add more info on updating CRD failure
=> bug: additional logging context

itest/starboard-operator/behavior/behavior.go, itest/starboard/starboard_cli_test.go, pkg/configauditreport/controller.go, pkg/kube/object.go, pkg/kube/object_test.go, pkg/operator/controller/configauditreport.go, pkg/starboard/config.go, pkg/vulnerabilityreport/controller.go
=> fix: revert CronJobs to batch/v1beta1

deploy/crd/ciskubebenchreports.crd.yaml, deploy/crd/clustercompliancedetailreports.crd.yaml, deploy/crd/clustercompliancereports.crd.yaml, deploy/crd/clusterconfigauditreports.crd.yaml, deploy/crd/clustervulnerabilityreports.crd.yaml, deploy/crd/configauditreports.crd.yaml, deploy/crd/kubehunterreports.crd.yaml, deploy/crd/vulnerabilityreports.crd.yaml, deploy/helm/Chart.yaml, deploy/specs/nsa-1.0.yaml, deploy/static/01-starboard-operator.ns.yaml, deploy/static/02-starboard-operator.rbac.yaml, deploy/static/03-starboard-operator.config.yaml, deploy/static/04-starboard-operator.policies.yaml, deploy/static/05-starboard-operator.deployment.yaml, deploy/static/starboard.yaml, docs/crds/clustercompliance-report.md, mkdocs.yml
=> release: prepare v0.15.1

deploy/crd/clusterconfigauditreports.crd.yaml, deploy/crd/configauditreports.crd.yaml, deploy/static/starboard.yaml, docs/cli/getting-started.md, docs/operator/getting-started.md, docs/tutorials/writing-custom-configuration-audit-policies.md
Critical is spelled incorrectly in a number of places.
```
grep -ril critial |
xargs sed -i \
-e 's/CRITIAL/CRITICAL/g' \
-e 's/Critial/Critical/g' \
-e 's/critial/critical/g'
```
=> fix: critial is a typo

.github/workflows/build.yaml
=> chore(ci): cancel any in-flight jobs for the same PR branch

.github/workflows/build.yaml, .github/workflows/publish-docs.yaml, .github/workflows/publish-helm-chart.yaml, .github/workflows/release-snapshot.yaml
=> chore(ci): set permissions granted to the GITHUB_TOKEN

.github/workflows/publish-docs.yaml
=> chore(ci): grant contents permission in docs publishing workflow

.github/workflows/release-snapshot.yaml, README.md
=> chore(ci): fix release snapshot workflow

.goreleaser.yaml, Makefile, build/starboard-operator-ubi8/Dockerfile.ubi8
This PR contains changes in the .goreleaser yaml ,  Makefile and addition of Dockerfile with ubi8-minimal as base Image for OCP Certification of Starboard-Operator.
=> Build Starboard Operator based on Red Hat Universal Base Image 8 Minimal

pkg/docker/config.go, pkg/docker/config_test.go
Modified Decode() in docker config pkg to use SplitN rather than Split. This allows GCR auths to be split that contain multiple : characters.
- Close #857
=> Modified Decode() to use SplitN rather than Split

deploy/helm/templates/config.yaml, deploy/helm/values.yaml
This patch adds the trivy mirror configuration to the starboard operator
helm chart. This particular implementation is made to match the
definitions from the documentation and therefore uses two layers for the
object and singular terminology.
The patch is required because currently there is no way than post
deployment patching of the configmap in order to utilise this feature,
which works against the intention of helm. It was also very confusing to
find the documentation providing this option, but the helm chart not
doing so, therefore this patch should help to cleanup potential
confusion.
https://aquasecurity.github.io/starboard/v0.15.4/vulnerability-scanning/trivy/#settings
=> feat(trivy): add mirror config in helm chart

pkg/configauditreport/builder.go
roles can have different chars which are not supported in crd names eg '_', capital letter
previous fix was only handling capital letter, this fix will handle other usecases as well.
fixes: #1355
=> fix: Fix crd names error for roles

go.mod, go.sum
To maintain compatibility with previous KE versions, we initially introduced the result. New feature to all Rego scripts on the server level. However, we encountered an error within StarBoard. This problem arises from the utilization of "dots in rule heads," which is not compatible with the current OPA version employed by StarBoard. As a resolution, updated the OPA version used within StarBoard to v0.46.1. Reference: https://github.com/open-policy-agent/opa/issues/4653
We were observing vulnerabilities in image, this PR will resolve the vulnerabilities as well.
=> opa version upgrade to latest

.goreleaser.yaml, Makefile, build/starboard-operator/Dockerfile.fips.ubi8, cmd/starboard-operator/fipsonly.go
As part of this PR, we are adding support for fips enabled images which is needed for fips compliance This PR has following changes
- Add docker file for fips enabled image
- Add makefile commands to generate fips enabled binary
- Add goreleaser support to release starboard-operator with fips enable image
- fix deprecated parameter from goreleaser i.e Replacements
=> chore: release fips enabled images

.goreleaser.yaml, build/starboard-operator/Dockerfile.fips.ubi9, build/starboard-operator/Dockerfile.ubi9
As part of this PR, new images will be build using ubi9 as base image. 
We will continue to have ubi8 images until we deprecate them fully
=> chore: Add ubi9 images for starboard-operator

.goreleaser.yaml
build_id was not incorrect for fips based images
=> fix: release pipeline failure

.goreleaser.yaml
Pipeline is getting failed due to out of memory error. 
So removing some artifacts that are not required to be released
=> fix: goreleaser pipeline failure

.github/workflows/release.yaml
- Implemented cleanup steps for Docker and KIND resources to prevent disk space errors.
=> chore: Add cleanup and disk usage checks to GitHub Actions workflow.

pkg/configauditreport/controller.go, pkg/operator/predicate/predicate.go, pkg/operator/predicate/predicate_test.go
In a scaled 800-node cluster, running the starboard-operator with KE results in 1600 pods being created for kube-bench. Since kube-bench is an internal Aqua component, its evaluation can be safely skipped. By excluding kube-bench from the starboard-operator's scope, we can reduce the overall memory consumption of the starboard-operator, optimizing its performance in large-scale environments.
=> perf: Exclude kube-bench pods from being evaluated in the starboard

.github/workflows/build.yaml, .github/workflows/publish-docs.yaml, .github/workflows/publish-helm-chart.yaml, .github/workflows/release-snapshot.yaml, .github/workflows/release.yaml
The builds are failing due to the deprecation of Ubuntu 20.04 in GitHub Actions. Updating the runs-on parameter to a supported version to fix it
- Close #XXX
Remove this section if you don't have related PRs.
=> chore: Update ubuntu version
